-- Planly 3.3B assignee completion authorization test plan.
-- Run in the existing Supabase test harness with OWNER_ID, ASSIGNEE_ID,
-- OTHER_MEMBER_ID, HOUSEHOLD_ID and TASK_CLIENT_ID fixtures.
-- Expected contract:
-- 1. ASSIGNEE_ID can call planly_set_assigned_task_completed(..., true).
-- 2. ASSIGNEE_ID can call it again with false.
-- 3. OTHER_MEMBER_ID receives 42501 for the same task.
-- 4. A non-household user receives 42501.
-- 5. ASSIGNEE_ID still cannot UPDATE planly_tasks directly because the owner-only RLS policy remains.
-- 6. ASSIGNEE_ID cannot change title/date/visibility/assignee/delete through this RPC; its only input mutation is completed.
-- 7. Once reassigned, the previous assignee receives 42501 and the new assignee can toggle completion.
-- 8. Once unshared/private, the assignee receives 42501.
-- 9. deleted_at rows return P0002.
--
-- The RPC rechecks assignment and current Household membership while holding the task row FOR UPDATE,
-- preventing stale assignment state from granting completion authority.
