// Planly 4.0E.1 — monthly workflow over the scoped/owned Budget model.
(()=>{'use strict';
const base=window.PlanlyBudgetUI,money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(n)||0)/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host=null,month=window.PlanlyBudgetMonth?.get?.()||window.PlanlyBudgetActiveMonth||new Date().toISOString().slice(0,7),viewer='',addWrapped=false,subview=null,changeBusy=false;window.PlanlyBudgetActiveMonth=month;
const api=()=>window.PlanlyBudget,state=()=>api().getState(),monthDate=m=>m+'-01',label=m=>new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(new Date(m+'-01T12:00:00'));
function setMonth(next){month=window.PlanlyBudgetMonth?.set?.(next)||next;window.PlanlyBudgetActiveMonth=month;return month}
function shift(m,n){const [y,mo]=m.split('-').map(Number),d=new Date(y,mo-1+n,1);return d.toISOString().slice(0,7)}
function entryDate(day=1){const [y,mo]=month.split('-').map(Number),last=new Date(y,mo,0).getDate();return month+'-'+String(Math.min(Math.max(Number(day)||1,1),last)).padStart(2,'0')}
function installEntryMonthGuard(){if(addWrapped||!api()?.addEntry)return;const original=api().addEntry;api().addEntry=args=>{const current=new Date().toISOString().slice(0,7),next={...args};if(month!==current&&String(next.entryDate||'').slice(0,7)===current)next.entryDate=entryDate(next.dueDay||1);return original(next)};addWrapped=true}
function style(){if(document.getElementById('planlyBudgetMonthlyStyle'))return;const s=document.createElement('style');s.id='planlyBudgetMonthlyStyle';s.textContent=`.budgetMonthBar{display:grid;grid-template-columns:48px 1fr 48px;align-items:center;gap:8px;margin:0 0 14px}.budgetMonthBar button{height:44px;border:1px solid var(--line);border-radius:14px;background:var(--card);color:var(--text);font-size:24px;touch-action:manipulation;-webkit-tap-highlight-color:transparent}.budgetMonthBar button:active{transform:scale(.96)}.budgetMonthBar button:disabled{opacity:.5}.budgetMonthLabel{text-align:center;font-weight:820}.budgetMonthLabel small{display:block;color:var(--muted);font-size:9px;font-weight:650;margin-top:2px}.budgetMonthSummary{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:0 0 14px}.budgetMonthStat{padding:10px;border-radius:14px;background:var(--cardSoft);text-align:center}.budgetMonthStat strong,.budgetMonthStat span{display:block}.budgetMonthStat strong{font-size:13px}.budgetMonthStat span{font-size:9px;color:var(--muted);margin-top:3px}.budgetTargetRow{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:11px 0;border-top:1px solid var(--line)}.budgetTargetRow input{width:92px;min-height:38px;border:1px solid var(--line);border-radius:11px;background:var(--cardSoft);color:var(--text);padding:0 9px;text-align:right}.budgetRecurringCallout{padding:12px 13px;border:1px solid var(--line);border-radius:15px;background:var(--cardSoft);margin-bottom:14px}.budgetRecurringCallout strong{display:block;font-size:12px}.budgetRecurringCallout p{font-size:10px;color:var(--muted);line-height:1.4;margin:4px 0 10px}.budgetRecurringCallout button{width:100%}`;document.head.appendChild(s)}
function rows(){return state().entries.filter(x=>String(x.entry_date).slice(0,7)===month)}
function recurringSources(){const previous=shift(month,-1),current=rows();return state().entries.filter(x=>x.owner_id===viewer&&String(x.entry_date).slice(0,7)===previous&&x.recurring_monthly).filter(x=>!current.some(y=>y.owner_id===viewer&&y.kind===x.kind&&y.category_id===x.category_id&&String(y.description||'').trim().toLowerCase()===String(x.description||'').trim().toLowerCase()))}
function inject(){if(!host||subview)return;window.PlanlyBudgetActiveMonth=month;const first=host.querySelector('.budgetScopeBar')||host.firstElementChild;if(!first)return;host.querySelector('.budgetMonthBar')?.remove();host.querySelector('.budgetMonthSummary')?.remove();host.querySelector('.budgetRecurringCallout')?.remove();const r=rows(),income=r.filter(x=>x.kind==='income').reduce((n,x)=>n+Number(x.amount_minor||0),0),planned=r.filter(x=>x.kind==='expense').reduce((n,x)=>n+Number(x.amount_minor||0),0),paid=r.filter(x=>x.kind==='expense'&&x.allocation_status==='paid').reduce((n,x)=>n+Number(x.amount_minor||0),0),due=recurringSources();first.insertAdjacentHTML('afterend',`<div class="budgetMonthBar"><button type="button" data-month-prev aria-label="Previous month">‹</button><div class="budgetMonthLabel">${esc(label(month))}<small>Monthly budget</small></div><button type="button" data-month-next aria-label="Next month">›</button></div><div class="budgetMonthSummary"><div class="budgetMonthStat"><strong class="budgetIncomeAmount">+${money(income)}</strong><span>Income</span></div><div class="budgetMonthStat"><strong>${money(planned)}</strong><span>Planned</span></div><div class="budgetMonthStat"><strong>${money(paid)}</strong><span>Paid</span></div></div>${due.length?`<div class="budgetRecurringCallout"><strong>${due.length} recurring item${due.length===1?'':'s'} ready for ${esc(label(month))}</strong><p>Carry forward only recurring items you created. Historical entries stay unchanged; the new month's copies start as planned.</p><button class="budgetBtn" type="button" data-month-carry>Carry forward my recurring items</button></div>`:''}`);host.querySelector('[data-month-prev]').onclick=()=>change(-1);host.querySelector('[data-month-next]').onclick=()=>change(1);host.querySelector('[data-month-carry]')?.addEventListener('click',carry);rewrite()}
function rewrite(){if(!host||subview)return;const s=state(),r=rows(),targets=s.targets.filter(x=>String(x.budget_month).slice(0,7)===month),hero=host.querySelector('.budgetHero');if(hero){const income=r.filter(x=>x.kind==='income').reduce((n,x)=>n+Number(x.amount_minor||0),0),expense=r.filter(x=>x.kind==='expense').reduce((n,x)=>n+Number(x.amount_minor||0),0),title=hero.querySelector('.budgetMuted'),balance=hero.querySelector('.budgetHeroBalance'),metrics=hero.querySelectorAll('.budgetMetric strong');if(title)title.textContent='Left to budget · '+label(month);if(balance)balance.textContent=money(income-expense);if(metrics[0])metrics[0].textContent='+'+money(income);if(metrics[1])metrics[1].textContent=money(expense)}for(const el of host.querySelectorAll('.budgetCat[data-cat]')){const id=el.dataset.cat,total=r.filter(x=>x.category_id===id).reduce((n,x)=>n+Number(x.amount_minor||0),0),t=targets.find(x=>x.category_id===id),small=el.querySelector('small'),amount=el.querySelector('.budgetCatAmount');if(amount)amount.textContent=money(total);if(small)small.textContent=r.filter(x=>x.category_id===id).length+' item'+(r.filter(x=>x.category_id===id).length===1?'':'s')+(t?' · '+money(t.amount_minor)+' budget':'')}if(api().canAdmin?.()){const card=[...host.querySelectorAll('.budgetCard')].find(x=>x.querySelector('.budgetSectionHead strong')?.textContent==='Budget categories');if(card&&!card.querySelector('[data-month-targets]')){const b=document.createElement('button');b.className='budgetLink';b.dataset.monthTargets='1';b.textContent='Set budgets';b.onclick=targetsView;card.querySelector('.budgetSectionHead')?.appendChild(b)}}}
async function change(delta){if(changeBusy||subview)return;changeBusy=true;const buttons=host?.querySelectorAll('.budgetMonthBar button')||[];buttons.forEach(b=>b.disabled=true);try{setMonth(shift(month,delta));await base.renderTab(host);inject()}finally{changeBusy=false}}
async function carry(){for(const x of recurringSources()){try{api().addEntry({kind:x.kind,amountMinor:x.amount_minor,categoryId:x.category_id,entryDate:entryDate(x.due_day||1),description:x.description,notes:x.notes||'',allocationStatus:'planned',dueDay:x.due_day,recurringMonthly:true})}catch(e){console.warn('Budget recurring carry',e)}}await base.renderTab(host);inject()}
function targetsView(){subview='targets';const s=state(),cats=s.categories.filter(x=>!x.archived&&x.kind==='expense'),targets=s.targets.filter(x=>String(x.budget_month).slice(0,7)===month);host.innerHTML=`<button class="budgetBack" data-target-back>‹ Budget</button><section class="budgetCard"><div class="budgetSectionHead"><div><strong>${esc(label(month))} category budgets</strong><div class="budgetMuted">Set how much of this month's income you intend to allocate to each category.</div></div></div>${cats.map(c=>{const t=targets.find(x=>x.category_id===c.id);return `<label class="budgetTargetRow"><span><strong>${esc(c.name)}</strong><small class="budgetMuted">Monthly target</small></span><input type="number" min="0" step="0.01" inputmode="decimal" data-target-cat="${esc(c.id)}" value="${((Number(t?.amount_minor)||0)/100).toFixed(2)}"></label>`}).join('')||'<div class="budgetEmpty">Create an expense category first.</div>'}<button class="budgetBtn budgetPrimary" data-target-save>Save monthly budgets</button></section>`;host.querySelector('[data-target-back]').onclick=async()=>{subview=null;await base.renderTab(host);inject()};host.querySelector('[data-target-save]').onclick=async()=>{try{host.querySelectorAll('[data-target-cat]').forEach(input=>api().setTarget({categoryId:input.dataset.targetCat,budgetMonth:monthDate(month),amountMinor:Math.round(Number(input.value||0)*100)}));subview=null;await base.renderTab(host);inject()}catch(e){alert(e?.message||String(e))}}}
async function renderTab(target){style();host=target||host;month=window.PlanlyBudgetMonth?.get?.()||window.PlanlyBudgetActiveMonth||month;window.PlanlyBudgetActiveMonth=month;installEntryMonthGuard();try{const client=window.supabase?.createClient&&window.PLANLY_SUPABASE_CONFIG?window.supabase.createClient(PLANLY_SUPABASE_CONFIG.url,PLANLY_SUPABASE_CONFIG.publishableKey):null;const session=client?await client.auth.getSession():null;viewer=session?.data?.session?.user?.id||viewer}catch{}if(subview==='targets'){targetsView();return}await base.renderTab(host);inject()}
window.PlanlyBudgetUI={...base,renderTab};
})();
