// Planly 4.0B — personal budget vertical slice.
// Loaded after the primary app. Budget state is account-scoped and independent from task/project rendering.
(()=>{
'use strict';
const CACHE_PREFIX='planly-budget-cache-v1:';
const PENDING_PREFIX='planly-budget-pending-v1:';
const CONFLICT_PREFIX='planly-budget-conflicts-v1:';
const money=n=>Number.isFinite(Number(n))?Math.round(Number(n)):0;
const id=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const account=()=>window.__planlyBudgetOwnerId||'';
const key=p=>account()?p+account():'';
const read=(p,f)=>{const k=key(p);if(!k)return f;try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(p,v)=>{const k=key(p);if(k)localStorage.setItem(k,JSON.stringify(v))};
let state={scope:null,categories:[],targets:[],entries:[],versions:{scope:0,categories:{},targets:{},entries:{}}};
const persist=()=>write(CACHE_PREFIX,{version:1,savedAt:new Date().toISOString(),state});
const restore=()=>{const d=read(CACHE_PREFIX,null);if(d?.version===1&&d.state){state=d.state;return true}return false};
const pending=()=>read(PENDING_PREFIX,[]), conflicts=()=>read(CONFLICT_PREFIX,[]);
function stage(kind,action,row,baseVersion){const list=pending().filter(x=>!(x.kind===kind&&x.id===row.id));list.push({kind,action,id:row.id,row,baseVersion:Number(baseVersion||0),operationId:id(),queuedAt:Date.now(),status:'queued'});write(PENDING_PREFIX,list)}
function clearPending(kind,rowId){write(PENDING_PREFIX,pending().filter(x=>!(x.kind===kind&&x.id===rowId)))}
function recordConflict(op,server){const list=conflicts().filter(x=>!(x.kind===op.kind&&x.id===op.id));list.push({kind:op.kind,id:op.id,local:op.row,server:server||null,baseVersion:op.baseVersion,recordedAt:Date.now()});write(CONFLICT_PREFIX,list);const rows=pending();const hit=rows.find(x=>x.kind===op.kind&&x.id===op.id);if(hit)hit.status='conflict';write(PENDING_PREFIX,rows)}
function client(){const c=window.__planlySupabaseClient;if(!c)throw new Error('Planly Cloud session is not ready.');return c}
const tableFor=k=>({scope:'planly_budget_scopes',category:'planly_budget_categories',target:'planly_budget_targets',entry:'planly_budget_entries'})[k];
async function fetchRow(kind,rowId){const {data,error}=await client().from(tableFor(kind)).select('*').eq('id',rowId).maybeSingle();if(error)throw error;return data||null}
async function push(op){const table=tableFor(op.kind),row={...op.row};delete row.cloud_version;delete row.created_at;delete row.updated_at;if(op.action==='delete')row.deleted_at=new Date().toISOString();if(op.baseVersion){const {data,error}=await client().from(table).update(row).eq('id',op.id).eq('cloud_version',op.baseVersion).select('*').maybeSingle();if(error)throw error;if(!data){recordConflict(op,await fetchRow(op.kind,op.id));return false}setVersion(op.kind,op.id,data.cloud_version)}else{const {data,error}=await client().from(table).insert(row).select('*').single();if(error){recordConflict(op,await fetchRow(op.kind,op.id).catch(()=>null));return false}setVersion(op.kind,op.id,data.cloud_version)}clearPending(op.kind,op.id);return true}
function setVersion(kind,rowId,v){if(kind==='scope')state.versions.scope=Number(v||0);else state.versions[kind+'s'][rowId]=Number(v||0)}
async function replay(){if(!navigator.onLine||!account())return;for(const op of pending().filter(x=>x.status!=='conflict')){try{await push(op)}catch(e){if(!navigator.onLine)break;console.warn('Planly budget sync',e)}}persist()}
async function bootstrap(){if(!account())return false;restore();if(!navigator.onLine)return true;const c=client();const {data:scopes,error}=await c.from('planly_budget_scopes').select('*').eq('scope_type','personal').eq('owner_id',account()).is('deleted_at',null);if(error)throw error;let scope=scopes?.[0]||null;if(!scope){scope={id:id(),owner_id:account(),scope_type:'personal',household_id:null,name:'Personal Budget',currency_code:'GBP',client_updated_at:Date.now(),deleted_at:null};stage('scope','upsert',scope,0);await replay();scope=await fetchRow('scope',scope.id)}state.scope=scope;if(!scope)return false;state.versions.scope=Number(scope.cloud_version||0);const [cats,targets,entries]=await Promise.all(['planly_budget_categories','planly_budget_targets','planly_budget_entries'].map(t=>c.from(t).select('*').eq('scope_id',scope.id).is('deleted_at',null)));for(const r of [cats,targets,entries])if(r.error)throw r.error;state.categories=cats.data||[];state.targets=targets.data||[];state.entries=entries.data||[];for(const x of state.categories)setVersion('category',x.id,x.cloud_version);for(const x of state.targets)setVersion('target',x.id,x.cloud_version);for(const x of state.entries)setVersion('entry',x.id,x.cloud_version);persist();await replay();return true}
function addEntry({kind='expense',amountMinor,categoryId=null,entryDate,note=''}){if(!state.scope)throw new Error('Budget is not ready.');const row={id:id(),scope_id:state.scope.id,owner_id:account(),category_id:categoryId||null,entry_kind:kind,amount_minor:Math.abs(money(amountMinor)),entry_date:entryDate||new Date().toISOString().slice(0,10),note:String(note||'').slice(0,500),client_updated_at:Date.now(),deleted_at:null};state.entries.unshift(row);stage('entry','upsert',row,0);persist();replay();return row}
function updateEntry(rowId,patch){const row=state.entries.find(x=>x.id===rowId);if(!row)throw new Error('Budget entry not found.');Object.assign(row,patch,{owner_id:account(),scope_id:state.scope.id,client_updated_at:Date.now()});stage('entry','upsert',row,state.versions.entries[rowId]||0);persist();replay();return row}
function deleteEntry(rowId){const row=state.entries.find(x=>x.id===rowId);if(!row)return;state.entries=state.entries.filter(x=>x.id!==rowId);stage('entry','delete',row,state.versions.entries[rowId]||0);persist();replay()}
function addCategory({name,kind='expense'}){if(!state.scope)throw new Error('Budget is not ready.');const row={id:id(),scope_id:state.scope.id,owner_id:account(),name:String(name||'').trim().slice(0,80),category_kind:kind,sort_order:state.categories.length,client_updated_at:Date.now(),deleted_at:null};if(!row.name)throw new Error('Category name is required.');state.categories.push(row);stage('category','upsert',row,0);persist();replay();return row}
function setTarget({categoryId,monthStart,amountMinor}){let row=state.targets.find(x=>x.category_id===categoryId&&x.month_start===monthStart);if(!row){row={id:id(),scope_id:state.scope.id,category_id:categoryId,owner_id:account(),month_start:monthStart,target_minor:Math.max(0,money(amountMinor)),client_updated_at:Date.now(),deleted_at:null};state.targets.push(row);stage('target','upsert',row,0)}else{row.target_minor=Math.max(0,money(amountMinor));row.client_updated_at=Date.now();stage('target','upsert',row,state.versions.targets[row.id]||0)}persist();replay();return row}
function summary(month=new Date().toISOString().slice(0,7)){const rows=state.entries.filter(x=>String(x.entry_date||'').slice(0,7)===month),income=rows.filter(x=>x.entry_kind==='income').reduce((s,x)=>s+money(x.amount_minor),0),expense=rows.filter(x=>x.entry_kind==='expense').reduce((s,x)=>s+money(x.amount_minor),0);return {month,income,expense,balance:income-expense,entries:rows.length}}
function exposeSession(ownerId,supabaseClient){window.__planlyBudgetOwnerId=ownerId||'';window.__planlySupabaseClient=supabaseClient||null;if(ownerId)bootstrap().catch(e=>console.warn('Planly budget bootstrap',e))}
window.PlanlyBudget={bootstrap,replay,restore,addEntry,updateEntry,deleteEntry,addCategory,setTarget,summary,getState:()=>structuredClone(state),getPending:pending,getConflicts:conflicts,adoptSession:exposeSession};
window.addEventListener('online',()=>replay());
})();
