// Planly 4.3 — safe service-worker update coordination.
(()=>{'use strict';
const STATE={registration:null,waiting:null,prompt:null,reloading:false};
const editing=()=>!!(document.documentElement.classList.contains('sheetOpen')||document.querySelector('.sheetWrap.open,.projectsWrap.open,.taskActionWrap.open,.focusWrap.open,.timelineWrap.open,.planDayWrap.open')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName));
function style(){if(document.getElementById('planlyUpdateStyle'))return;const s=document.createElement('style');s.id='planlyUpdateStyle';s.textContent='.planlyUpdatePrompt{position:fixed;left:50%;transform:translateX(-50%);bottom:calc(86px + env(safe-area-inset-bottom));z-index:120;width:min(calc(100% - 24px),696px);background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:16px;padding:12px 13px;box-shadow:var(--shadowLift);display:flex;align-items:center;gap:10px}.planlyUpdatePrompt>div{min-width:0;flex:1}.planlyUpdatePrompt strong,.planlyUpdatePrompt span{display:block}.planlyUpdatePrompt span{font-size:11px;color:var(--muted);margin-top:2px}.planlyUpdatePrompt button{min-height:38px;border:0;border-radius:11px;background:var(--accent);color:var(--accentText);padding:0 12px;font-weight:750}.planlyUpdatePrompt button.secondary{background:var(--bg);color:var(--text);border:1px solid var(--line)}';document.head.appendChild(s)}
function removePrompt(){STATE.prompt?.remove();STATE.prompt=null}
function activate(){const worker=STATE.waiting||STATE.registration?.waiting;if(!worker)return;STATE.waiting=worker;worker.postMessage({type:'SKIP_WAITING'})}
function show(waiting){STATE.waiting=waiting||STATE.registration?.waiting;if(!STATE.waiting||STATE.prompt)return;style();const p=document.createElement('div');p.className='planlyUpdatePrompt';p.innerHTML='<div><strong>Planly update ready</strong><span>Apply the new version when you are ready.</span></div><button type="button" data-update-now>Update</button><button type="button" class="secondary" data-update-later>Later</button>';p.querySelector('[data-update-now]').onclick=()=>{if(editing()){p.querySelector('span').textContent='Finish or close what you are editing, then update.';return}activate()};p.querySelector('[data-update-later]').onclick=removePrompt;document.body.appendChild(p);STATE.prompt=p}
function trackInstalling(reg){const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)show(reg.waiting||worker)})}
async function init(){if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});STATE.registration=reg;if(reg.waiting&&navigator.serviceWorker.controller)show(reg.waiting);reg.addEventListener('updatefound',()=>trackInstalling(reg));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(STATE.reloading)return;STATE.reloading=true;removePrompt();location.reload()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')reg.update().catch(()=>{})});setInterval(()=>reg.update().catch(()=>{}),60*60*1000)}catch(err){window.__planlySwBoot={status:'error',name:err?.name||'',message:err?.message||String(err)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.PlanlyUpdate={check:()=>STATE.registration?.update(),apply:()=>{if(!editing())activate()},hasUpdate:()=>!!(STATE.waiting||STATE.registration?.waiting)};
})();
