// Planly 4.0L.2 — persistence-confirmed Budget edit/remove actions.
(()=>{'use strict';
const api=()=>window.PlanlyBudget;
let host=null;
function style(){if(document.getElementById('planlyBudgetActions40lStyle'))return;const s=document.createElement('style');s.id='planlyBudgetActions40lStyle';s.textContent=`.budgetLifecycleBtn.danger{color:var(--danger,#c43b4d)}.budgetCategoryRemove{width:100%;margin-top:10px;color:var(--danger,#c43b4d);border-color:color-mix(in srgb,var(--danger,#c43b4d) 28%,var(--line))}.budgetRemoveNote{font-size:10px;color:var(--muted);line-height:1.4;margin-top:8px}.budgetManageCategoryActions{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.budgetManageCategoryActions button{min-height:30px;padding:0 9px;font-size:9px}.budgetCategoryInlineEdit{width:min(220px,100%);min-height:36px;border:1px solid var(--line);border-radius:10px;background:var(--cardSoft);color:var(--text);padding:0 9px;font-weight:760}`;document.head.appendChild(s)}
function mutationError(kind,id,label){const a=api(),pending=a.getPending().find(x=>x.kind===kind&&x.id===id),conflict=a.getConflicts().find(x=>x.kind===kind&&x.id===id);if(conflict)throw Error(`${label} changed on another device. Refresh Budget and try again.`);if(navigator.onLine&&pending)throw Error(`${label} could not be saved to the cloud. It is still queued for sync.`)}
async function persistedEntryUpdate(id,patch){const a=api();a.updateEntry(id,patch);await a.replay();mutationError('entry',id,'This payment');return true}
async function persistedDelete(id){const a=api();a.deleteEntry(id);await a.replay();mutationError('entry',id,'This payment');return true}
async function persistedCategoryUpdate(id,patch){const a=api();a.updateCategory(id,patch);await a.replay();mutationError('category',id,'This category');return true}
async function persistedCategoryArchive(id){return persistedCategoryUpdate(id,{archived:true})}
function selectedCategory(){const el=host?.querySelector('[data-act="allocation"][data-category]');return el?.dataset.category||''}
function rerender(){return window.PlanlyBudgetUI?.renderTab?.(host)}
function decorateCategory(){if(!host)return;const id=selectedCategory();if(!id||host.querySelector('[data-budget-remove-category]'))return;const a=api(),state=a.getState(),category=state.categories.find(x=>x.id===id);if(!category||!a.canAdmin())return;const card=host.querySelector('.budgetCard');if(!card)return;const b=document.createElement('button');b.type='button';b.className='budgetBtn budgetCategoryRemove';b.dataset.budgetRemoveCategory='1';b.textContent='Remove category';b.onclick=async()=>{const used=state.entries.some(x=>x.category_id===id)||state.targets.some(x=>x.category_id===id),message=used?`Remove ${category.name} from active Budget categories? Existing payment history will be kept.`:`Remove ${category.name} from Budget categories?`;if(!confirm(message))return;b.disabled=true;try{await persistedCategoryArchive(id);window.dispatchEvent(new CustomEvent('planly:budget-view-changed',{detail:{from:'category',to:'dashboard'}}));await rerender()}catch(err){b.disabled=false;alert(err?.message||String(err))}};card.appendChild(b);if(used){const note=document.createElement('div');note.className='budgetRemoveNote';note.textContent='Removing a category hides it from active budgeting but keeps its existing payment history.';card.appendChild(note)}}
function beginRename(row,category,actions){const info=row.children[1],strong=info?.querySelector('strong');if(!info||!strong)return;const input=document.createElement('input');input.className='budgetCategoryInlineEdit';input.value=category.name||'';input.maxLength=80;strong.replaceWith(input);actions.innerHTML='<button type="button" class="budgetLifecycleBtn" data-category-save>Save</button><button type="button" class="budgetLifecycleBtn" data-category-cancel>Cancel</button>';const cancel=()=>{input.replaceWith(strong);actions.remove();row.dataset.manageDecorated='';decorateManage()};actions.querySelector('[data-category-cancel]').onclick=e=>{e.stopPropagation();cancel()};actions.querySelector('[data-category-save]').onclick=async e=>{e.stopPropagation();const name=input.value.trim();if(!name){alert('Category name is required.');return}e.currentTarget.disabled=true;try{await persistedCategoryUpdate(category.id,{name});await rerender()}catch(err){e.currentTarget.disabled=false;alert(err?.message||String(err))}};input.onclick=e=>e.stopPropagation();input.focus();input.select()}
function decorateManage(){if(!host?.querySelector('#budgetCategoryForm'))return;const a=api();if(!a.canAdmin())return;const state=a.getState();host.querySelectorAll('[data-manage-category]').forEach(row=>{if(row.dataset.manageDecorated==='1')return;const id=row.dataset.manageCategory,category=state.categories.find(x=>x.id===id&&!x.archived);if(!category)return;row.dataset.manageDecorated='1';const info=row.children[1];if(!info)return;const actions=document.createElement('div');actions.className='budgetManageCategoryActions';actions.innerHTML='<button type="button" class="budgetLifecycleBtn" data-category-edit>Edit</button><button type="button" class="budgetLifecycleBtn danger" data-category-remove>Remove</button>';info.appendChild(actions);actions.querySelector('[data-category-edit]').onclick=e=>{e.stopPropagation();beginRename(row,category,actions)};actions.querySelector('[data-category-remove]').onclick=async e=>{e.stopPropagation();if(!confirm(`Remove ${category.name} from active Budget categories?`))return;const b=e.currentTarget;b.disabled=true;try{await persistedCategoryArchive(id);await rerender()}catch(err){b.disabled=false;alert(err?.message||String(err))}}})}
function decorate(){queueMicrotask(()=>{decorateCategory();decorateManage()})}
const base=window.PlanlyBudgetUI;if(!base?.renderTab)return;const baseRender=base.renderTab.bind(base);async function renderTab(target){style();host=target||host;const result=await baseRender(host);decorate();return result}
window.addEventListener('planly:budget-view-changed',()=>decorate());
window.PlanlyBudgetUI={...base,renderTab};window.PlanlyBudgetActions={persistedEntryUpdate,persistedDelete,persistedCategoryUpdate,persistedCategoryArchive};
})();
