// Planly 4.3B — non-invasive Safari tap/freeze diagnostics.
(()=>{'use strict';
const KEY='planly-safari-diagnostics-v1',MAX=80;let events=[];
try{events=JSON.parse(sessionStorage.getItem(KEY)||'[]');if(!Array.isArray(events))events=[]}catch{events=[]}
const trim=s=>String(s??'').replace(/\s+/g,' ').trim().slice(0,180);
const elInfo=el=>{if(!(el instanceof Element))return null;const r=el.getBoundingClientRect(),cs=getComputedStyle(el);return {tag:el.tagName,id:el.id||'',cls:trim(el.className),text:trim(el.textContent),z:cs.zIndex,pointer:cs.pointerEvents,display:cs.display,visibility:cs.visibility,position:cs.position,rect:[Math.round(r.left),Math.round(r.top),Math.round(r.width),Math.round(r.height)]}};
function blockers(){const out=[];for(const el of document.querySelectorAll('body *')){const cs=getComputedStyle(el);if(cs.display==='none'||cs.visibility==='hidden'||cs.pointerEvents==='none')continue;const r=el.getBoundingClientRect(),z=Number.parseInt(cs.zIndex,10);if((cs.position==='fixed'||cs.position==='absolute')&&Number.isFinite(z)&&z>=20&&r.width>=innerWidth*.8&&r.height>=innerHeight*.55)out.push(elInfo(el))}return out.slice(-12)}
async function swInfo(){try{const reg=await navigator.serviceWorker?.getRegistration('./');return {controller:navigator.serviceWorker?.controller?.scriptURL||'',active:reg?.active?.state||'',waiting:reg?.waiting?.state||'',installing:reg?.installing?.state||''}}catch(err){return {error:trim(err?.message||err)}}}
async function snapshot(reason,extra={}){const active=document.activeElement,points=[[innerWidth/2,Math.min(90,innerHeight-1)],[innerWidth/2,innerHeight/2],[innerWidth/2,Math.max(1,innerHeight-100)]],snap={at:new Date().toISOString(),reason,href:location.href,visibility:document.visibilityState,online:navigator.onLine,scrollY:Math.round(scrollY),htmlClass:document.documentElement.className,bodyClass:document.body?.className||'',htmlOverflow:getComputedStyle(document.documentElement).overflow,bodyOverflow:getComputedStyle(document.body).overflow,bodyPosition:getComputedStyle(document.body).position,active:elInfo(active),hit:points.map(([x,y])=>elInfo(document.elementFromPoint(x,y))),blockers:blockers(),sw:await swInfo(),boot:window.__planlySwBoot||null,runtime:window.PlanlyUpdate?{hasUpdate:!!window.PlanlyUpdate.hasUpdate?.()}:null,...extra};events.push(snap);if(events.length>MAX)events=events.slice(-MAX);try{sessionStorage.setItem(KEY,JSON.stringify(events))}catch{}return snap}
function recordError(kind,value){snapshot(kind,{error:{message:trim(value?.message||value?.reason?.message||value?.reason||value),stack:trim(value?.error?.stack||value?.reason?.stack||'')}})}
addEventListener('error',e=>recordError('error',e));addEventListener('unhandledrejection',e=>recordError('unhandledrejection',e));
addEventListener('pageshow',e=>snapshot('pageshow',{persisted:!!e.persisted}),{once:true});document.addEventListener('visibilitychange',()=>snapshot('visibilitychange'));
let down=null;document.addEventListener('pointerdown',e=>{down={t:performance.now(),x:e.clientX,y:e.clientY,target:elInfo(e.target)}},{capture:true,passive:true});document.addEventListener('pointerup',e=>{if(!down)return;const dt=Math.round(performance.now()-down.t),move=Math.round(Math.hypot(e.clientX-down.x,e.clientY-down.y));if(dt<900&&move<18)setTimeout(()=>snapshot('tap',{tap:{dt,move,down:down.target,up:elInfo(e.target)}}),80);down=null},{capture:true,passive:true});
async function report(){const now=await snapshot('manual-report'),payload={generatedAt:new Date().toISOString(),userAgent:navigator.userAgent,screen:{w:screen.width,h:screen.height,dpr:devicePixelRatio},current:now,events};return JSON.stringify(payload,null,2)}
async function copy(){const text=await report();try{await navigator.clipboard.writeText(text);return true}catch{try{const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;opacity:0;pointer-events:none';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}}
function button(){if(document.getElementById('planlySafariDiag'))return;const b=document.createElement('button');b.id='planlySafariDiag';b.type='button';b.textContent='Copy freeze diagnostics';b.setAttribute('aria-label','Copy Safari freeze diagnostics');b.style.cssText='position:fixed;right:12px;top:calc(env(safe-area-inset-top) + 8px);z-index:18;border:1px solid var(--line);background:var(--card);color:var(--muted);border-radius:10px;padding:7px 9px;font-size:9px;opacity:.42';b.onclick=async()=>{const ok=await copy();const old=b.textContent;b.textContent=ok?'Diagnostics copied':'Copy failed';setTimeout(()=>b.textContent=old,1800)};document.body.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',button,{once:true});else button();
window.PlanlySafariDiagnostics={snapshot,report,copy,clear(){events=[];try{sessionStorage.removeItem(KEY)}catch{}},getEvents(){return events.slice()}};
})();
