// Planly 4.0C — explicit personal/household budget scopes with isolated offline journals.
(()=>{'use strict';
const CACHE='planly-budget-cache-v2:',PENDING='planly-budget-pending-v2:',CONFLICT='planly-budget-conflicts-v2:',ACTIVE='planly-budget-active-scope-v1:';
const emptyVersions=()=>({scope:0,categories:{},targets:{},entries:{}}),emptyState=()=>({scope:null,scopes:[],categories:[],targets:[],entries:[],versions:emptyVersions()});
let owner='',sb=null,replayPromise=null,state=emptyState(),activeType='personal';
const uuid=()=>crypto.randomUUID(),now=()=>Date.now(),minor=n=>Math.max(0,Math.round(Number(n)||0)),baseKey=p=>owner?p+owner:'',scopeKey=(p,type=activeType)=>owner?p+owner+':'+type:'';
const readKey=(k,f)=>{if(!k)return f;try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},writeKey=(k,v)=>{if(k)localStorage.setItem(k,JSON.stringify(v))};
const read=(p,f)=>readKey(scopeKey(p),f),write=(p,v)=>writeKey(scopeKey(p),v),activePref=()=>readKey(baseKey(ACTIVE),'personal');
function normalizeState(raw){const s=raw&&typeof raw==='object'?raw:{},v=s.versions&&typeof s.versions==='object'?s.versions:{};return {scope:s.scope||null,scopes:Array.isArray(s.scopes)?s.scopes:[],categories:Array.isArray(s.categories)?s.categories:[],targets:Array.isArray(s.targets)?s.targets:[],entries:Array.isArray(s.entries)?s.entries:[],versions:{scope:Number(v.scope||0),categories:v.categories&&typeof v.categories==='object'?v.categories:{},targets:v.targets&&typeof v.targets==='object'?v.targets:{},entries:v.entries&&typeof v.entries==='object'?v.entries:{}}}}
const persist=()=>write(CACHE,{version:2,savedAt:new Date().toISOString(),scopeType:activeType,state}),restore=()=>{const d=read(CACHE,null);if(d?.version===2&&d.state){state=normalizeState(d.state);return true}return false};
const pending=()=>read(PENDING,[]),conflicts=()=>read(CONFLICT,[]),table=k=>({scope:'planly_budget_scopes',category:'planly_budget_categories',target:'planly_budget_targets',entry:'planly_budget_entries'})[k];
function setVersion(k,id,v){if(!state.versions)state.versions=emptyVersions();if(k==='scope')state.versions.scope=Number(v||0);else{const bucket=k+'s';state.versions[bucket]??={};state.versions[bucket][id]=Number(v||0)}}
function stage(kind,action,row,baseVersion){const list=pending().filter(x=>!(x.kind===kind&&x.id===row.id));list.push({kind,action,id:row.id,row:{...row},baseVersion:Number(baseVersion||0),operationId:uuid(),queuedAt:now(),status:'queued'});write(PENDING,list)}
function clearPending(op){write(PENDING,pending().filter(x=>!(x.kind===op.kind&&x.id===op.id&&x.operationId===op.operationId)))}function clearConflict(k,id){write(CONFLICT,conflicts().filter(x=>!(x.kind===k&&x.id===id)))}
async function fetchRow(k,id){const {data,error}=await sb.from(table(k)).select('*').eq('id',id).maybeSingle();if(error)throw error;return data||null}
function conflict(op,server){const current=pending().find(x=>x.kind===op.kind&&x.id===op.id);if(!current||current.operationId!==op.operationId)return;const list=conflicts().filter(x=>!(x.kind===op.kind&&x.id===op.id));list.push({kind:op.kind,id:op.id,local:op.row,server,baseVersion:op.baseVersion,recordedAt:now()});write(CONFLICT,list);current.status='conflict';write(PENDING,pending().map(x=>x.kind===op.kind&&x.id===op.id&&x.operationId===op.operationId?current:x))}
function clean(row){const r={...row};delete r.cloud_version;delete r.created_at;delete r.updated_at;return r}function sameInsert(op,server){return !!server&&op.baseVersion===0&&server.id===op.id&&server.client_id&&server.client_id===op.row.client_id&&server.owner_id===op.row.owner_id}function acceptServer(op,server){setVersion(op.kind,op.id,server.cloud_version);clearPending(op);clearConflict(op.kind,op.id)}
async function push(op){const r=clean(op.row);if(op.action==='delete')r.deleted_at=new Date().toISOString();let res;if(op.baseVersion)res=await sb.from(table(op.kind)).update(r).eq('id',op.id).eq('cloud_version',op.baseVersion).select('*').maybeSingle();else res=await sb.from(table(op.kind)).insert(r).select('*').single();if(res.error){if(!op.baseVersion){const server=await fetchRow(op.kind,op.id).catch(()=>null);if(sameInsert(op,server)){acceptServer(op,server);return true}if(server){conflict(op,server);return false}}throw res.error}if(op.baseVersion&&!res.data){conflict(op,await fetchRow(op.kind,op.id));return false}acceptServer(op,res.data);return true}
async function reconcileInsertJournal(){for(const op of pending().filter(x=>x.baseVersion===0)){const server=await fetchRow(op.kind,op.id).catch(()=>null);if(sameInsert(op,server))acceptServer(op,server)}}async function replayNow(){if(!navigator.onLine||!owner||!sb)return;await reconcileInsertJournal();for(const op of pending().filter(x=>x.status!=='conflict')){try{await push(op)}catch(e){if(!navigator.onLine)break;console.warn('Planly budget sync',e)}}persist()}function replay(){if(replayPromise)return replayPromise;replayPromise=replayNow().finally(()=>{replayPromise=null;if(navigator.onLine&&owner&&sb&&pending().some(x=>x.status!=='conflict'))queueMicrotask(()=>replay())});return replayPromise}
async function householdInfo(){const {data,error}=await sb.from('planly_household_members').select('household_id,role').eq('user_id',owner).limit(1);if(error)throw error;return data?.[0]||null}
async function listScopes(){const {data,error}=await sb.from('planly_budget_scopes').select('*').is('deleted_at',null);if(error)throw error;return data||[]}
async function createPersonal(){const row={id:uuid(),owner_id:owner,household_id:null,scope_type:'personal',name:'Personal Budget',currency:'GBP',client_id:'personal-'+uuid(),client_created_at:now(),client_updated_at:now(),deleted_at:null};activeType='personal';stage('scope','upsert',row,0);await replay();return fetchRow('scope',row.id)}
async function createHouseholdScope(){const membership=await householdInfo();if(!membership)throw Error('Create or join a Household first.');if(membership.role!=='owner')throw Error('Only the Household owner can create the shared budget.');const existing=(await listScopes()).find(x=>x.scope_type==='household'&&x.household_id===membership.household_id);if(existing)return existing;const row={id:uuid(),owner_id:owner,household_id:membership.household_id,scope_type:'household',name:'Household Budget',currency:'GBP',client_id:'household-'+uuid(),client_created_at:now(),client_updated_at:now(),deleted_at:null};activeType='household';stage('scope','upsert',row,0);await replay();return fetchRow('scope',row.id)}
async function loadScope(type,{create=false}={}){activeType=type==='household'?'household':'personal';state=emptyState();restore();if(!navigator.onLine&&state.scope?.scope_type===activeType)return true;if(!owner||!sb)return false;let scopes=await listScopes();let scope=scopes.find(x=>x.scope_type===activeType&&(activeType==='personal'?x.owner_id===owner:true))||null;if(!scope&&activeType==='personal')scope=await createPersonal();if(!scope&&activeType==='household'&&create)scope=await createHouseholdScope();state.scopes=scopes;state.scope=scope;if(!scope){persist();return false}setVersion('scope',scope.id,scope.cloud_version);const results=await Promise.all(['planly_budget_categories','planly_budget_targets','planly_budget_entries'].map(t=>sb.from(t).select('*').eq('scope_id',scope.id).is('deleted_at',null)));for(const r of results)if(r.error)throw r.error;[state.categories,state.targets,state.entries]=results.map(r=>r.data||[]);for(const x of state.categories)setVersion('category',x.id,x.cloud_version);for(const x of state.targets)setVersion('target',x.id,x.cloud_version);for(const x of state.entries)setVersion('entry',x.id,x.cloud_version);await reconcileInsertJournal();persist();await replay();return true}
async function bootstrap(){if(!owner||!sb)return false;let preferred=activePref();if(preferred!=='household')preferred='personal';try{const ok=await loadScope(preferred);if(ok)return true}catch(e){console.warn('Budget preferred scope',e)}return loadScope('personal')}
async function switchScope(type){const next=type==='household'?'household':'personal';if(next===activeType&&state.scope)return true;if(pending().some(x=>x.status!=='conflict'))await replay();writeKey(baseKey(ACTIVE),next);const ok=await loadScope(next);window.dispatchEvent(new CustomEvent('planly-budget-scope-changed',{detail:{scopeType:next,ready:ok}}));return ok}
async function ensureHouseholdScope(){writeKey(baseKey(ACTIVE),'household');const ok=await loadScope('household',{create:true});window.dispatchEvent(new CustomEvent('planly-budget-scope-changed',{detail:{scopeType:'household',ready:ok}}));return ok}
function canAdmin(){return state.scope?.scope_type==='personal'||state.scope?.owner_id===owner}
function addCategory({name,kind='expense',iconKey='wallet',colorKey='violet'}){if(!state.scope)throw Error('Budget is not ready.');if(!canAdmin())throw Error('Only the Household budget owner can manage shared categories.');const t=String(name||'').trim();if(!t)throw Error('Category name is required.');const row={id:uuid(),scope_id:state.scope.id,owner_id:owner,client_id:'category-'+uuid(),name:t.slice(0,80),kind,icon_key:String(iconKey||'wallet').slice(0,32),color_key:String(colorKey||'violet').slice(0,24),sort_order:state.categories.length,archived:false,client_created_at:now(),client_updated_at:now(),deleted_at:null};state.categories.push(row);stage('category','upsert',row,0);persist();replay();return row}
function addEntry({kind='expense',amountMinor,categoryId,entryDate,description='',notes='',allocationStatus='planned',dueDay=null,recurringMonthly=true}){if(!state.scope)throw Error('Budget is not ready.');const cat=state.categories.find(x=>x.id===categoryId&&!x.archived);if(!cat||cat.kind!==kind)throw Error('Choose a matching budget category.');const row={id:uuid(),scope_id:state.scope.id,category_id:cat.id,owner_id:owner,client_id:'entry-'+uuid(),kind,amount_minor:minor(amountMinor),entry_date:entryDate||new Date().toISOString().slice(0,10),description:String(description).slice(0,160),notes:String(notes).slice(0,500),allocation_status:allocationStatus==='paid'?'paid':'planned',due_day:dueDay?Math.min(31,Math.max(1,Number(dueDay))):null,recurring_monthly:recurringMonthly!==false,client_created_at:now(),client_updated_at:now(),deleted_at:null};state.entries.unshift(row);stage('entry','upsert',row,0);persist();replay();return row}
function updateEntry(id,patch){const row=state.entries.find(x=>x.id===id);if(!row)throw Error('Budget payment not found.');if(row.owner_id!==owner)throw Error('You can only edit budget entries you added.');const next={...patch};for(const k of ['owner_id','scope_id','client_id','id'])delete next[k];Object.assign(row,next,{client_updated_at:now()});stage('entry','upsert',row,state.versions.entries[id]||0);persist();replay();return row}function updateCategory(id,patch){if(!canAdmin())throw Error('Only the Household budget owner can manage shared categories.');const row=state.categories.find(x=>x.id===id);if(!row)throw Error('Budget category not found.');const next={...patch};for(const k of ['owner_id','scope_id','client_id','id'])delete next[k];Object.assign(row,next,{client_updated_at:now()});stage('category','upsert',row,state.versions.categories[id]||0);persist();replay();return row}function deleteEntry(id){const row=state.entries.find(x=>x.id===id);if(!row)return;if(row.owner_id!==owner)throw Error('You can only delete budget entries you added.');state.entries=state.entries.filter(x=>x.id!==id);stage('entry','delete',row,state.versions.entries[id]||0);persist();replay()}
function setTarget({categoryId,budgetMonth,amountMinor}){if(!canAdmin())throw Error('Only the Household budget owner can change shared targets.');let row=state.targets.find(x=>x.category_id===categoryId&&x.budget_month===budgetMonth);if(!row){row={id:uuid(),scope_id:state.scope.id,category_id:categoryId,owner_id:owner,client_id:'target-'+uuid(),budget_month:budgetMonth,amount_minor:minor(amountMinor),client_created_at:now(),client_updated_at:now(),deleted_at:null};state.targets.push(row);stage('target','upsert',row,0)}else{row.amount_minor=minor(amountMinor);row.client_updated_at=now();stage('target','upsert',row,state.versions.targets[row.id]||0)}persist();replay();return row}
function summary(month=new Date().toISOString().slice(0,7)){const rows=state.entries.filter(x=>String(x.entry_date).slice(0,7)===month),income=rows.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount_minor),0),expense=rows.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount_minor),0);return {month,income,expense,balance:income-expense,entries:rows.length}}
async function init(){if(!window.supabase?.createClient||!window.PLANLY_SUPABASE_CONFIG)return;sb=window.supabase.createClient(PLANLY_SUPABASE_CONFIG.url,PLANLY_SUPABASE_CONFIG.publishableKey);const {data}=await sb.auth.getSession();owner=data.session?.user?.id||'';if(owner)await bootstrap();sb.auth.onAuthStateChange((_e,s)=>{const next=s?.user?.id||'';if(next!==owner){owner=next;replayPromise=null;state=emptyState();activeType='personal';if(owner)bootstrap().catch(console.warn)}})}
window.PlanlyBudget={bootstrap,replay,restore,switchScope,ensureHouseholdScope,addCategory,updateCategory,addEntry,updateEntry,deleteEntry,setTarget,summary,getState:()=>structuredClone(state),getScopeType:()=>activeType,canAdmin,getPending:pending,getConflicts:conflicts};window.addEventListener('online',()=>bootstrap().catch(console.warn));setTimeout(()=>init().catch(e=>console.warn('Planly budget init',e)),0);
})();
