// Planly 4.0C.5 — persistent household budget scope UI layered over the 4.0B renderer.
(()=>{'use strict';
const wait=ms=>new Promise(r=>setTimeout(r,ms)),base=window.PlanlyBudgetUI;
function style(){if(document.getElementById('planlyBudgetScopeStyle'))return;const s=document.createElement('style');s.id='planlyBudgetScopeStyle';s.textContent=`.budgetScopeBar{display:grid;grid-template-columns:1fr 1fr;gap:4px;padding:4px;margin-bottom:14px;border:1px solid var(--line);border-radius:16px;background:var(--cardSoft)}.budgetScopeBar button{min-height:44px;border:0;border-radius:12px;background:transparent;color:var(--muted);font-weight:760}.budgetScopeBar button.active{background:var(--card);color:var(--text);box-shadow:0 2px 10px rgba(0,0,0,.07)}.budgetScopeSetup{padding:22px 16px;text-align:center}.budgetScopeSetup strong{font-size:18px}.budgetScopeSetup p{font-size:12px;color:var(--muted);line-height:1.45}`;document.head.appendChild(s)}
function scopeBar(a){const t=a.getScopeType?.()||a.getState()?.scope?.scope_type||'personal';return `<div class="budgetScopeBar"><button type="button" data-budget-scope="personal" class="${t==='personal'?'active':''}">Me</button><button type="button" data-budget-scope="household" class="${t==='household'?'active':''}">Household</button></div>`}
async function rerender(host){const composed=window.PlanlyBudgetUI?.renderTab;if(typeof composed==='function'&&composed!==render)return composed(host);return render(host,{bootstrap:false})}
function bindScope(host){host.querySelectorAll('[data-budget-scope]').forEach(b=>b.onclick=async()=>{const next=b.dataset.budgetScope;if(next===window.PlanlyBudget.getScopeType?.())return;b.disabled=true;try{await window.PlanlyBudget.switchScope(next);await rerender(host)}catch(e){alert(e?.message||String(e));b.disabled=false}});const create=host.querySelector('[data-budget-create-household]');if(create)create.onclick=async()=>{create.disabled=true;create.textContent='Creating…';try{await window.PlanlyBudget.ensureHouseholdScope();await rerender(host)}catch(e){alert(e?.message||String(e));create.disabled=false;create.textContent='Create Household Budget'}}}
function bindNavigation(host,a){host.querySelectorAll('[data-act],[data-cat]').forEach(el=>{const original=el.onclick;if(typeof original!=='function'||el.dataset.scopeWrapped==='1')return;el.dataset.scopeWrapped='1';el.onclick=function(ev){const result=original.call(this,ev);queueMicrotask(()=>decorate(host,a));return result}});host.querySelectorAll('form').forEach(form=>{const original=form.onsubmit;if(typeof original!=='function'||form.dataset.scopeWrapped==='1')return;form.dataset.scopeWrapped='1';form.onsubmit=function(ev){const result=original.call(this,ev);queueMicrotask(()=>decorate(host,a));return result}})}
function decorate(host,a){if(!host?.isConnected)return;style();host.querySelector('.budgetScopeBar')?.remove();const type=a.getScopeType?.()||'personal',shared=type==='household';host.insertAdjacentHTML('afterbegin',scopeBar(a));host.querySelectorAll('.budgetStatus').forEach(el=>{if(el.textContent.includes('Personal budget'))el.textContent=el.textContent.replace('Personal budget',shared?'Household budget':'Personal budget')});bindScope(host);bindNavigation(host,a)}
/* Budget opens instantly from the data it already holds; it only waits for the server when nothing is loaded yet.
   Data older than BUDGET_FRESH_MS is refreshed in the background, then redrawn through the existing invalidation event. */
const BUDGET_FRESH_MS=60000;let budgetLoadedAt=Date.now(),budgetBackgroundLoad=null;
function budgetBackgroundRefresh(a){if(budgetBackgroundLoad||!navigator.onLine||Date.now()-budgetLoadedAt<BUDGET_FRESH_MS)return;budgetBackgroundLoad=Promise.resolve(a.bootstrap()).then(()=>{budgetLoadedAt=Date.now();window.dispatchEvent(new CustomEvent('planly:budget-invalidated',{detail:{reason:'background-refresh'}}))}).catch(e=>console.warn('Budget background refresh',e)).finally(()=>{budgetBackgroundLoad=null})}
async function render(host,{bootstrap=true}={}){style();const a=window.PlanlyBudget;if(!a||!base?.renderTab||!host)return;if(bootstrap){if(!a.getState?.()?.scope){await a.bootstrap();budgetLoadedAt=Date.now()}else budgetBackgroundRefresh(a)}const type=a.getScopeType?.()||'personal',state=a.getState();if(type==='household'&&!state.scope){host.innerHTML=scopeBar(a)+`<section class="budgetCard budgetScopeSetup"><strong>Set up Household Budget</strong><p>This creates a separate shared budget. Your Personal budget stays private and nothing is copied into Household automatically.</p><button class="budgetBtn budgetPrimary" data-budget-create-household>Create Household Budget</button><div class="budgetStatus">If you are a household member rather than its owner, the owner needs to create the shared budget first.</div></section>`;bindScope(host);return}await base.renderTab(host);await wait(0);decorate(host,a)}
window.addEventListener('planly:budget-ui-rendered',()=>{const host=document.getElementById('view'),a=window.PlanlyBudget;if(host&&a)queueMicrotask(()=>decorate(host,a))});
window.PlanlyBudgetUI={...base,renderTab:render};
})();
