// Planly 4.0N.2 — authoritative Budget mutations with classified failure states and deterministic Manage decoration.
(()=>{'use strict';
const api=()=>window.PlanlyBudget;
let host=null,client=null;
function db(){if(client)return client;if(!window.supabase?.createClient||!window.PLANLY_SUPABASE_CONFIG)throw Error('Budget cloud connection is unavailable.');client=window.PlanlySupabase?.get?.();return client}
function style(){if(document.getElementById('planlyBudgetActions40lStyle'))return;const s=document.createElement('style');s.id='planlyBudgetActions40lStyle';s.textContent=`.budgetLifecycleBtn.danger{color:var(--danger,#c43b4d)}.budgetMutationState{font-size:10px;font-weight:760;margin-top:6px}.budgetMutationState.pending{color:var(--muted)}.budgetMutationState.error{color:var(--danger,#c43b4d)}.budgetMutationState.saved{color:var(--success,#15945f)}.budgetCategoryRemove{width:100%;margin-top:10px;color:var(--danger,#c43b4d);border-color:color-mix(in srgb,var(--danger,#c43b4d) 28%,var(--line))}.budgetRemoveNote{font-size:10px;color:var(--muted);line-height:1.4;margin-top:8px}.budgetManageCategoryActions{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.budgetManageCategoryActions button{min-height:30px;padding:0 9px;font-size:9px}.budgetCategoryInlineEdit{width:min(220px,100%);min-height:36px;border:1px solid var(--line);border-radius:10px;background:var(--cardSoft);color:var(--text);padding:0 9px;font-weight:760}`;document.head.appendChild(s)}
function mutablePatch(kind,patch){const allowed=kind==='entry'?['description','amount_minor','category_id','entry_date','notes','allocation_status','due_day','recurring_monthly','show_on_today','today_lead_days','deleted_at']:['name','kind','icon_key','color_key','sort_order','archived','deleted_at'];const out={};for(const k of allowed)if(Object.prototype.hasOwnProperty.call(patch,k))out[k]=patch[k];out.client_updated_at=Date.now();return out}
function current(kind,id){const s=api().getState(),rows=kind==='entry'?s.entries:s.categories,row=rows.find(x=>x.id===id),versions=kind==='entry'?s.versions?.entries:s.versions?.categories;return {state:s,row,version:Number(versions?.[id]||row?.cloud_version||0)}}
function scopeAllows(row,state){const scope=state.scope,viewer=api().getViewerId?.()||'';if(!scope||!row)return false;if(scope.scope_type==='personal')return scope.owner_id===viewer&&row.owner_id===viewer;if(scope.scope_type==='household')return true;return false}
async function classifyZero(kind,id,expected){const table=kind==='entry'?'planly_budget_entries':'planly_budget_categories';const {data,error}=await db().from(table).select('id,cloud_version,deleted_at').eq('id',id).maybeSingle();if(error)return {code:'unresolved',message:'Planly could not verify why this change was rejected. Nothing has been removed locally.'};if(!data)return {code:'unresolved',message:'This item is no longer visible to this account. Refresh Budget before trying again.'};if(Number(data.cloud_version)!==Number(expected))return {code:'conflict',message:'This item changed on another device. Refresh Budget before changing it again.',server:data};return {code:'denied',message:'You cannot change this item with the current Budget permissions.',server:data}}
async function mutate(kind,id,patch,{remove=false}={}){const a=api(),{state,row,version}=current(kind,id);if(!row)throw Object.assign(Error(kind==='entry'?'Budget payment not found.':'Budget category not found.'),{code:'missing'});if(!scopeAllows(row,state))throw Object.assign(Error('You cannot change this item.'),{code:'denied'});if(!navigator.onLine)throw Object.assign(Error('You are offline. This change has not been applied; reconnect and try again.'),{code:'offline'});if(!version)throw Object.assign(Error('This item has not finished syncing yet. Wait for sync before changing it.'),{code:'pending'});const table=kind==='entry'?'planly_budget_entries':'planly_budget_categories',payload=mutablePatch(kind,remove?{...patch,deleted_at:new Date().toISOString()}:patch);const res=await db().from(table).update(payload).eq('id',id).eq('cloud_version',version).select('*').maybeSingle();if(res.error)throw Object.assign(Error(res.error.message||'Budget change could not be saved.'),{code:res.error.code||'database'});if(!res.data){const why=await classifyZero(kind,id,version);throw Object.assign(Error(why.message),why)}if(Number(res.data.cloud_version)<=version)throw Object.assign(Error('Budget change was not version-confirmed by the server.'),{code:'version'});await a.bootstrap();window.dispatchEvent(new CustomEvent('planly:budget-mutation-confirmed',{detail:{kind,id,action:remove?'delete':'update',row:res.data}}));return {status:'confirmed',row:res.data}}
async function persistedEntryUpdate(id,patch){return mutate('entry',id,patch)}
async function persistedDelete(id){return mutate('entry',id,{}, {remove:true})}
async function persistedCategoryUpdate(id,patch){return mutate('category',id,patch)}
async function persistedCategoryArchive(id){return persistedCategoryUpdate(id,{archived:true})}
function selectedCategory(){const el=host?.querySelector('[data-act="allocation"][data-category]');return el?.dataset.category||''}
function rerender(){return window.PlanlyBudgetUI?.renderTab?.(host)}
function decorateCategory(){if(!host)return;const id=selectedCategory();if(!id||host.querySelector('[data-budget-remove-category]'))return;const a=api(),state=a.getState(),category=state.categories.find(x=>x.id===id);if(!category||!a.canAdmin())return;const card=host.querySelector('.budgetCard');if(!card)return;const used=state.entries.some(x=>x.category_id===id);const b=document.createElement('button');b.type='button';b.className='budgetBtn budgetCategoryRemove';b.dataset.budgetRemoveCategory='1';b.textContent='Remove category';b.onclick=async()=>{const message=used?`Remove ${category.name} from active Budget categories? Existing payment history will be kept.`:`Remove ${category.name} from Budget categories?`;if(!confirm(message))return;b.disabled=true;try{await persistedCategoryArchive(id);await rerender()}catch(err){b.disabled=false;alert(err?.message||String(err))}};card.appendChild(b);if(used){const note=document.createElement('div');note.className='budgetRemoveNote';note.textContent='Removing a category hides it from active budgeting but keeps its existing payment history.';card.appendChild(note)}}
function beginRename(row,category,actions){const info=row.children[1],strong=info?.querySelector('strong');if(!info||!strong)return;const input=document.createElement('input');input.className='budgetCategoryInlineEdit';input.value=category.name||'';input.maxLength=80;strong.replaceWith(input);actions.innerHTML='<button type="button" class="budgetLifecycleBtn" data-category-save>Save</button><button type="button" class="budgetLifecycleBtn" data-category-cancel>Cancel</button>';const cancel=()=>{input.replaceWith(strong);actions.remove();row.dataset.manageDecorated='';decorateManage()};actions.querySelector('[data-category-cancel]').onclick=e=>{e.stopPropagation();cancel()};actions.querySelector('[data-category-save]').onclick=async e=>{e.stopPropagation();const name=input.value.trim();if(!name){alert('Category name is required.');return}const button=e.currentTarget;button.disabled=true;button.textContent='Saving…';try{await persistedCategoryUpdate(category.id,{name});strong.textContent=name;input.replaceWith(strong);actions.remove();row.dataset.manageDecorated='';decorateManage()}catch(err){button.disabled=false;button.textContent='Save';alert(err?.message||String(err))}};input.onclick=e=>e.stopPropagation();input.focus();input.select()}
function decorateManage(){if(!host?.querySelector('#budgetCategoryForm'))return;const a=api();if(!a.canAdmin())return;const state=a.getState();host.querySelectorAll('[data-manage-category]').forEach(row=>{if(row.dataset.manageDecorated==='1')return;const id=row.dataset.manageCategory,category=state.categories.find(x=>x.id===id&&!x.archived);if(!category)return;row.dataset.manageDecorated='1';const info=row.children[1];if(!info)return;const actions=document.createElement('div');actions.className='budgetManageCategoryActions';actions.innerHTML='<button type="button" class="budgetLifecycleBtn" data-category-edit>Edit</button><button type="button" class="budgetLifecycleBtn danger" data-category-remove>Remove</button>';info.appendChild(actions);actions.querySelector('[data-category-edit]').onclick=e=>{e.stopPropagation();beginRename(row,category,actions)};actions.querySelector('[data-category-remove]').onclick=async e=>{e.stopPropagation();if(!confirm(`Remove ${category.name} from active Budget categories?`))return;const b=e.currentTarget;b.disabled=true;b.textContent='Removing…';try{await persistedCategoryArchive(id);row.remove();decorateManage()}catch(err){b.disabled=false;b.textContent='Remove';alert(err?.message||String(err))}}})}
function decorate(){queueMicrotask(()=>{decorateCategory();decorateManage()})}
const base=window.PlanlyBudgetUI;if(!base?.renderTab)return;const baseRender=base.renderTab.bind(base);async function renderTab(target){style();host=target||host;const result=await baseRender(host);decorate();return result}
window.addEventListener('planly:budget-view-changed',()=>decorate());
window.addEventListener('planly:budget-ui-rendered',()=>decorate());
window.PlanlyBudgetUI={...base,renderTab};window.PlanlyBudgetActions={mutate,persistedEntryUpdate,persistedDelete,persistedCategoryUpdate,persistedCategoryArchive,classifyZero};
})();
