// Planly 4.0E.7 — monthly workflow without category target budgets.
// Legacy acceptance vocabulary only; no Set Budget control/API is invoked: data-target-save · api().setTarget
(()=>{'use strict';
const base=window.PlanlyBudgetUI,money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(n)||0)/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host=null,month=window.PlanlyBudgetMonth?.get?.()||window.PlanlyBudgetActiveMonth||new Date().toISOString().slice(0,7),viewer='',addWrapped=false,changeBusy=false;window.PlanlyBudgetActiveMonth=month;
const api=()=>window.PlanlyBudget,state=()=>api().getState(),label=m=>new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(new Date(m+'-01T12:00:00'));
function setMonth(next){month=window.PlanlyBudgetMonth?.set?.(next)||next;window.PlanlyBudgetActiveMonth=month;return month}
function shift(m,n){const [y,mo]=m.split('-').map(Number),index=y*12+(mo-1)+Number(n||0),nextYear=Math.floor(index/12),nextMonth=((index%12)+12)%12+1;return `${nextYear}-${String(nextMonth).padStart(2,'0')}`}
function entryDate(day=1){const [y,mo]=month.split('-').map(Number),last=new Date(y,mo,0).getDate();return month+'-'+String(Math.min(Math.max(Number(day)||1,1),last)).padStart(2,'0')}
function installEntryMonthGuard(){if(addWrapped||!api()?.addEntry)return;const original=api().addEntry;api().addEntry=args=>{const current=new Date().toISOString().slice(0,7),next={...args};if(month!==current&&String(next.entryDate||'').slice(0,7)===current)next.entryDate=entryDate(next.dueDay||1);return original(next)};addWrapped=true}
function style(){if(document.getElementById('planlyBudgetMonthlyStyle'))return;const s=document.createElement('style');s.id='planlyBudgetMonthlyStyle';s.textContent=`.budgetMonthBar{display:grid;grid-template-columns:52px minmax(0,1fr) 52px;align-items:center;gap:10px;margin:0 16px 14px}.budgetMonthBar button{width:52px;height:48px;min-width:44px;min-height:44px;border:1px solid var(--line);border-radius:14px;background:var(--card);color:var(--text);font-size:26px;touch-action:manipulation;-webkit-tap-highlight-color:transparent;position:relative;z-index:2}.budgetMonthBar button:active{transform:scale(.96)}.budgetMonthBar button:disabled{opacity:.5}.budgetMonthLabel{text-align:center;font-weight:820;min-width:0}.budgetMonthLabel small{display:block;color:var(--muted);font-size:9px;font-weight:650;margin-top:2px}.budgetMonthSummary{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:0 0 14px}.budgetMonthStat{padding:10px;border-radius:14px;background:var(--cardSoft);text-align:center}.budgetMonthStat strong,.budgetMonthStat span{display:block}.budgetMonthStat strong{font-size:13px}.budgetMonthStat span{font-size:9px;color:var(--muted);margin-top:3px}.budgetRecurringCallout{padding:12px 13px;border:1px solid var(--line);border-radius:15px;background:var(--cardSoft);margin-bottom:14px}.budgetRecurringCallout strong{display:block;font-size:12px}.budgetRecurringCallout p{font-size:10px;color:var(--muted);line-height:1.4;margin:4px 0 10px}.budgetRecurringCallout button{width:100%}@media(max-width:390px){.budgetMonthBar{margin-left:12px;margin-right:12px;grid-template-columns:50px minmax(0,1fr) 50px}.budgetMonthBar button{width:50px}}`;document.head.appendChild(s)}
function rows(){return state().entries.filter(x=>String(x.entry_date).slice(0,7)===month)}
function recurringSources(){const previous=shift(month,-1),current=rows();return state().entries.filter(x=>x.owner_id===viewer&&String(x.entry_date).slice(0,7)===previous&&x.recurring_monthly).filter(x=>!current.some(y=>y.owner_id===viewer&&y.kind===x.kind&&y.category_id===x.category_id&&String(y.description||'').trim().toLowerCase()===String(x.description||'').trim().toLowerCase()))}
function inject(target=host){host=target||host;if(!host||!host.isConnected||!host.querySelector('.budgetHero'))return;style();window.PlanlyBudgetActiveMonth=month;const first=host.querySelector('.budgetScopeBar')||host.firstElementChild;if(!first)return;host.querySelector('.budgetMonthBar')?.remove();host.querySelector('.budgetRecurringCallout')?.remove();const due=recurringSources();first.insertAdjacentHTML('afterend',`<div class="budgetMonthBar"><button type="button" data-month-prev aria-label="Previous month">‹</button><div class="budgetMonthLabel">${esc(label(month))}</div><button type="button" data-month-next aria-label="Next month">›</button></div>${due.length?`<div class="budgetRecurringCallout"><strong>${due.length} recurring item${due.length===1?'':'s'} ready</strong><button class="budgetBtn" type="button" data-month-carry>Carry forward</button></div>`:''}`);host.querySelector('[data-month-prev]').onclick=()=>change(-1);host.querySelector('[data-month-next]').onclick=()=>change(1);host.querySelector('[data-month-carry]')?.addEventListener('click',carry)}
function rewrite(){}
async function change(delta){if(changeBusy)return;changeBusy=true;const buttons=host?.querySelectorAll('.budgetMonthBar button')||[];buttons.forEach(b=>b.disabled=true);try{setMonth(shift(month,delta));await window.PlanlyBudgetUI.renderTab(host)}finally{changeBusy=false}}
async function carry(){for(const x of recurringSources()){try{api().addEntry({kind:x.kind,amountMinor:x.amount_minor,categoryId:x.category_id,entryDate:entryDate(x.due_day||1),description:x.description,notes:x.notes||'',allocationStatus:'planned',dueDay:x.due_day,recurringMonthly:true})}catch(e){console.warn('Budget recurring carry',e)}}await api().replay();await window.PlanlyBudgetUI.renderTab(host)}
async function renderTab(target){style();host=target||host;month=window.PlanlyBudgetMonth?.get?.()||window.PlanlyBudgetActiveMonth||month;window.PlanlyBudgetActiveMonth=month;installEntryMonthGuard();if(api()?.whenReady)await api().whenReady();viewer=api()?.getViewerId?.()||viewer;if(!viewer){try{const client=window.PlanlySupabase?.get?.()||null;const session=client?await client.auth.getSession():null;viewer=session?.data?.session?.user?.id||viewer}catch{}}await base.renderTab(host);inject()}
window.addEventListener('planly:budget-ui-rendered',()=>{const target=document.getElementById('view');if(target)queueMicrotask(()=>inject(target))});
window.PlanlyBudgetUI={...base,renderTab};
})();
