// Planly 4.0L — reliable mobile Budget removal actions layered over the existing Budget renderers.
(()=>{'use strict';
const api=()=>window.PlanlyBudget;
let host=null;
function style(){if(document.getElementById('planlyBudgetActions40lStyle'))return;const s=document.createElement('style');s.id='planlyBudgetActions40lStyle';s.textContent=`.budgetLifecycleBtn.danger{color:var(--danger,#c43b4d)}.budgetCategoryRemove{width:100%;margin-top:10px;color:var(--danger,#c43b4d);border-color:color-mix(in srgb,var(--danger,#c43b4d) 28%,var(--line))}.budgetRemoveNote{font-size:10px;color:var(--muted);line-height:1.4;margin-top:8px}`;document.head.appendChild(s)}
async function persistedDelete(id){const a=api();a.deleteEntry(id);await a.replay();const pending=a.getPending().find(x=>x.kind==='entry'&&x.id===id),conflict=a.getConflicts().find(x=>x.kind==='entry'&&x.id===id);if(conflict)throw Error('This payment changed on another device. Refresh Budget before deleting it.');if(navigator.onLine&&pending)throw Error('The payment could not be removed from the cloud. It is still queued for sync.');return true}
async function persistedCategoryArchive(id){const a=api();a.updateCategory(id,{archived:true});await a.replay();const pending=a.getPending().find(x=>x.kind==='category'&&x.id===id),conflict=a.getConflicts().find(x=>x.kind==='category'&&x.id===id);if(conflict)throw Error('This category changed on another device. Refresh Budget before removing it.');if(navigator.onLine&&pending)throw Error('The category could not be removed from the cloud. It is still queued for sync.');return true}
function selectedCategory(){const el=host?.querySelector('[data-act="allocation"][data-category]');return el?.dataset.category||''}
function decoratePayments(){if(!host)return;const categoryId=selectedCategory();if(!categoryId)return;const month=window.PlanlyBudgetActiveMonth||new Date().toISOString().slice(0,7),a=api(),viewer=a.getViewerId(),entries=a.getState().entries.filter(x=>x.kind==='expense'&&x.category_id===categoryId&&String(x.entry_date).slice(0,7)===month);const rows=[...host.querySelectorAll('.budgetAllocation')];rows.forEach((row,i)=>{const entry=entries[i],actions=row.querySelector('.budgetLifecycleActions');if(!entry||!actions||entry.owner_id!==viewer||actions.querySelector('[data-life-quick-delete]'))return;const b=document.createElement('button'),data=b.dataset;b.type='button';b.className='budgetLifecycleBtn danger';data.lifeQuickDelete='1';b.textContent='Delete';b.setAttribute('aria-label',`Delete ${entry.description||'payment'}`);b.onclick=async e=>{e.stopPropagation();if(!confirm(`Delete ${entry.description||'this payment'}?`))return;b.disabled=true;try{await persistedDelete(entry.id);await window.PlanlyBudgetUI.renderTab(host)}catch(err){b.disabled=false;alert(err?.message||String(err))}};actions.appendChild(b)})}
function decorateCategory(){if(!host)return;const id=selectedCategory();if(!id||host.querySelector('[data-budget-remove-category]'))return;const a=api(),state=a.getState(),category=state.categories.find(x=>x.id===id);if(!category||!a.canAdmin())return;const card=host.querySelector('.budgetCard');if(!card)return;const b=document.createElement('button');b.type='button';b.className='budgetBtn budgetCategoryRemove';b.dataset.budgetRemoveCategory='1';b.textContent='Remove category';b.onclick=async()=>{const used=state.entries.some(x=>x.category_id===id)||state.targets.some(x=>x.category_id===id),message=used?`Remove ${category.name} from active Budget categories? Existing payment history will be kept.`:`Remove ${category.name} from Budget categories?`;if(!confirm(message))return;b.disabled=true;try{await persistedCategoryArchive(id);await window.PlanlyBudgetUI.renderTab(host)}catch(err){b.disabled=false;alert(err?.message||String(err))}};card.appendChild(b);if(state.entries.some(x=>x.category_id===id)){const note=document.createElement('div');note.className='budgetRemoveNote';note.textContent='Removing a category hides it from active budgeting but keeps its existing payment history.';card.appendChild(note)}}
function decorate(){queueMicrotask(()=>{decoratePayments();decorateCategory()})}
const base=window.PlanlyBudgetUI;if(!base?.renderTab)return;const baseRender=base.renderTab.bind(base);async function renderTab(target){style();host=target||host;const result=await baseRender(host);decorate();return result}window.PlanlyBudgetUI={...base,renderTab};window.PlanlyBudgetActions={persistedDelete,persistedCategoryArchive};
})();
