// Planly 4.0P.3 — independent-review hardening for Budget state, household setup, refresh and entry identity.
(()=>{'use strict';
const a=()=>window.PlanlyBudget,money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(n)||0)/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalizedState(){const raw=a().__reviewBaseGetState(),s=structuredClone(raw),v=s.versions||={};v.categories||={};v.targets||={};v.entries||={};for(const row of s.categories||[])if(row?.id&&Number(row.cloud_version)>0)v.categories[row.id]=Number(row.cloud_version);for(const row of s.targets||[])if(row?.id&&Number(row.cloud_version)>0)v.targets[row.id]=Number(row.cloud_version);for(const row of s.entries||[])if(row?.id&&Number(row.cloud_version)>0)v.entries[row.id]=Number(row.cloud_version);return s}
function readPreference(owner){if(!owner)return'personal';try{return JSON.parse(localStorage.getItem('planly-budget-active-scope-v1:'+owner)||'"personal"')==='household'?'household':'personal'}catch{return'personal'}}
function installStateGuard(){const api=a();if(!api||api.__reviewHardened)return;api.__reviewBaseGetState=api.getState;api.getState=normalizedState;api.__reviewHardened=true;const baseBootstrap=api.bootstrap.bind(api);api.__reviewBaseBootstrap=baseBootstrap;api.bootstrap=async()=>{const owner=api.getViewerId?.()||'',pref=readPreference(owner),raw=api.__reviewBaseGetState?.();if(pref==='household'&&!(api.getScopeType?.()==='household'&&raw?.scope)){const ok=await api.switchScope('household');if(ok||api.getScopeType?.()==='household')return ok}return baseBootstrap()}}
function month(){return window.PlanlyBudgetMonth?.get?.()||window.PlanlyBudgetActiveMonth||new Date().toISOString().slice(0,7)}
function canChange(row,s){const scope=s.scope,viewer=a().getViewerId?.()||'';return !!row&&!!scope&&(scope.scope_type==='household'||(scope.scope_type==='personal'&&scope.owner_id===viewer&&row.owner_id===viewer))}
function rowHtml(x){return `<div class="budgetAllocation" data-budget-entry-id="${esc(x.id)}"><div><strong>${esc(x.description||'Payment')}</strong><small>${x.due_day?'Due day '+x.due_day+' · ':''}${x.recurring_monthly?'Monthly':'One-off'} · <span class="budgetState ${x.allocation_status==='paid'?'paid':'planned'}">${esc(x.allocation_status||'planned')}</span></small></div><div><strong>${money(x.amount_minor)}</strong></div></div>`}
function updateCategoryTotal(categoryId){const s=a().getState(),m=month(),total=s.entries.filter(x=>x.category_id===categoryId&&String(x.entry_date).slice(0,7)===m&&!x.deleted_at).reduce((n,x)=>n+Number(x.amount_minor||0),0),header=document.querySelector('[data-act="allocation"][data-category="'+CSS.escape(categoryId)+'"]')?.closest('.budgetSectionHead'),muted=header?.querySelector('.budgetMuted');if(muted)muted.textContent=money(total)+' budgeted'}
function editInline(row,entry){if(row.dataset.editing==='1')return;row.dataset.editing='1';const original=row.innerHTML;row.innerHTML=`<div style="grid-column:1/-1"><form data-review-edit-form class="budgetForm"><div><label>Name</label><input data-review-name maxlength="160" required value="${esc(entry.description||'')}"></div><div><label>Amount</label><input data-review-amount type="number" inputmode="decimal" min="0.01" step="0.01" required value="${(Number(entry.amount_minor||0)/100).toFixed(2)}"></div><div style="display:flex;gap:8px"><button class="budgetBtn budgetPrimary" type="submit">Save</button><button class="budgetBtn" type="button" data-review-cancel>Cancel</button></div><div class="budgetMutationState" data-review-state></div></form></div>`;row.querySelector('[data-review-cancel]').onclick=()=>{row.innerHTML=original;row.dataset.editing='';actions(row,entry)};row.querySelector('[data-review-edit-form]').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type="submit"]'),state=e.currentTarget.querySelector('[data-review-state]'),amount=Math.round(Number(e.currentTarget.querySelector('[data-review-amount]').value)*100),description=e.currentTarget.querySelector('[data-review-name]').value.trim();b.disabled=true;b.textContent='Saving…';state.textContent='Saving to Budget…';try{const result=await window.PlanlyBudgetActions.persistedEntryUpdate(entry.id,{amount_minor:amount,description});Object.assign(entry,result.row);row.outerHTML=rowHtml(result.row);const replacement=document.querySelector('[data-budget-entry-id="'+CSS.escape(entry.id)+'"]');if(replacement)actions(replacement,result.row);updateCategoryTotal(entry.category_id)}catch(err){b.disabled=false;b.textContent='Save';state.className='budgetMutationState error';state.textContent=err?.message||String(err)}}}
function actions(row,entry){const right=row.lastElementChild;if(!right||right.querySelector('[data-review-entry-actions]'))return;const s=a().getState();if(!canChange(entry,s))return;const wrap=document.createElement('div');wrap.className='budgetLifecycleActions';wrap.dataset.reviewEntryActions='1';wrap.innerHTML=`<button type="button" class="budgetLifecycleBtn ${entry.allocation_status==='paid'?'paid':''}" data-review-paid>${entry.allocation_status==='paid'?'Paid':'Mark paid'}</button><button type="button" class="budgetLifecycleBtn" data-review-edit>Edit</button><button type="button" class="budgetLifecycleBtn danger" data-review-delete>Delete</button>`;right.appendChild(wrap);wrap.querySelector('[data-review-paid]').onclick=async e=>{e.stopPropagation();const b=e.currentTarget;b.disabled=true;try{const paid=entry.allocation_status==='paid',r=await window.PlanlyBudgetActions.persistedEntryUpdate(entry.id,{allocation_status:paid?'planned':'paid'});Object.assign(entry,r.row);b.textContent=entry.allocation_status==='paid'?'Paid':'Mark paid';b.classList.toggle('paid',entry.allocation_status==='paid');const stateEl=row.querySelector('.budgetState');if(stateEl){stateEl.textContent=entry.allocation_status;stateEl.className='budgetState '+entry.allocation_status}b.disabled=false}catch(err){b.disabled=false;alert(err?.message||String(err))}};wrap.querySelector('[data-review-edit]').onclick=e=>{e.stopPropagation();editInline(row,entry)};wrap.querySelector('[data-review-delete]').onclick=async e=>{e.stopPropagation();if(!confirm(`Delete ${entry.description||'this payment'}?`))return;const b=e.currentTarget;b.disabled=true;b.textContent='Deleting…';try{await window.PlanlyBudgetActions.persistedDelete(entry.id);row.remove();updateCategoryTotal(entry.category_id)}catch(err){b.disabled=false;b.textContent='Delete';alert(err?.message||String(err))}}}
function patchCategory(){const host=document.querySelector('#view'),add=host?.querySelector('[data-act="allocation"][data-category]');if(!host||!add)return;const categoryId=add.dataset.category,s=a().getState(),entries=s.entries.filter(x=>x.kind==='expense'&&x.category_id===categoryId&&String(x.entry_date).slice(0,7)===month()&&!x.deleted_at),card=add.closest('.budgetCard');if(!card)return;for(const old of [...card.querySelectorAll('.budgetAllocation')])old.remove();card.querySelector('.budgetEmpty')?.remove();if(!entries.length){card.insertAdjacentHTML('beforeend','<div class="budgetEmpty">No payments in this category yet.</div>');return}card.insertAdjacentHTML('beforeend',entries.map(rowHtml).join(''));for(const row of card.querySelectorAll('[data-budget-entry-id]')){const entry=entries.find(x=>x.id===row.dataset.budgetEntryId);if(entry)actions(row,entry)}}
function installRenderGuard(){window.addEventListener('planly:budget-ui-rendered',()=>queueMicrotask(patchCategory));window.addEventListener('planly:budget-month',()=>queueMicrotask(patchCategory));const ui=window.PlanlyBudgetUI;if(!ui?.renderTab)return;const base=ui.renderTab.bind(ui);window.PlanlyBudgetUI={...ui,renderTab:async h=>{const r=await base(h);queueMicrotask(patchCategory);return r}}}
installStateGuard();installRenderGuard();
})();
