// Planly 4.0G.3 — derived monthly Budget insights without category targets.
(()=>{'use strict';
const base=window.PlanlyBudgetUI,money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(n)||0)/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host=null;
const api=()=>window.PlanlyBudget;
function style(){if(document.getElementById('planlyBudgetInsightsStyle'))return;const s=document.createElement('style');s.id='planlyBudgetInsightsStyle';s.textContent=`.budgetInsights{margin-bottom:14px}.budgetInsightGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.budgetInsight{padding:12px;border:1px solid var(--line);border-radius:15px;background:var(--cardSoft)}.budgetInsight strong,.budgetInsight span{display:block}.budgetInsight strong{font-size:15px}.budgetInsight span{font-size:9px;color:var(--muted);margin-top:4px}.budgetInsight.wide{grid-column:1/-1}.budgetInsightProgress{height:7px;border-radius:99px;background:var(--card);overflow:hidden;margin-top:9px}.budgetInsightProgress i{display:block;height:100%;background:var(--accent);border-radius:99px}.budgetInsightList{margin-top:10px}.budgetInsightRow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:9px 0;border-top:1px solid var(--line);font-size:11px}.budgetInsightRow:first-child{border-top:0}.budgetInsightRow span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.budgetInsightRow strong{font-size:11px}`;document.head.appendChild(s)}
function selectedMonth(){return window.PlanlyBudgetMonth?.get?.()||window.PlanlyBudgetActiveMonth||new Date().toISOString().slice(0,7)}
function build(){const s=api()?.getState?.();if(!s)return null;const month=selectedMonth(),entries=s.entries.filter(x=>String(x.entry_date||'').slice(0,7)===month),cats=new Map(s.categories.map(x=>[x.id,x])),income=entries.filter(x=>x.kind==='income').reduce((n,x)=>n+Number(x.amount_minor||0),0),expenses=entries.filter(x=>x.kind==='expense'),planned=expenses.reduce((n,x)=>n+Number(x.amount_minor||0),0),paid=expenses.filter(x=>x.allocation_status==='paid').reduce((n,x)=>n+Number(x.amount_minor||0),0),remaining=income-planned,coverage=planned?Math.min(100,Math.round(paid/planned*100)):0,categoryTotals=new Map();for(const x of expenses)categoryTotals.set(x.category_id,(categoryTotals.get(x.category_id)||0)+Number(x.amount_minor||0));const top=[...categoryTotals].map(([id,total])=>({name:cats.get(id)?.name||'Uncategorised',total})).sort((a,b)=>b.total-a.total).slice(0,3);return {income,planned,paid,remaining,coverage,top}}
function inject(target=host){host=target||host;if(!host||!host.isConnected||host.querySelector('.budgetInsights')||!host.querySelector('.budgetHero'))return;style();const d=build();if(!d)return;const after=host.querySelector('.budgetMonthSummary')||host.querySelector('.budgetHero'),budgetUse=d.income?Math.min(100,Math.round(d.planned/d.income*100)):0;after.insertAdjacentHTML('afterend',`<section class="budgetCard budgetInsights"><div class="budgetSectionHead"><div><strong>Monthly snapshot</strong><div class="budgetMuted">Derived from this month's budget only</div></div></div><div class="budgetInsightGrid"><div class="budgetInsight"><strong>${money(d.remaining)}</strong><span>Left after planned payments</span></div><div class="budgetInsight"><strong>${d.coverage}%</strong><span>Planned payments marked paid</span></div><div class="budgetInsight wide"><strong>${money(d.planned)} of ${money(d.income)}</strong><span>${budgetUse}% of income currently planned</span><div class="budgetInsightProgress"><i style="width:${budgetUse}%"></i></div></div></div>${d.top.length?`<div class="budgetInsightList">${d.top.map(x=>`<div class="budgetInsightRow"><span>${esc(x.name)}</span><strong>${money(x.total)}</strong></div>`).join('')}</div>`:''}</section>`)}
async function renderTab(target){style();host=target||host;await base.renderTab(host);inject()}
window.addEventListener('planly:budget-ui-rendered',()=>{const target=document.getElementById('view');if(target)queueMicrotask(()=>inject(target))});
window.PlanlyBudgetUI={...base,renderTab};window.dispatchEvent(new CustomEvent('planly:budget-invalidated',{detail:{reason:'ui-composed',version:'4.0G.3'}}));
})();
