// Planly 4.0N.3 — income lifecycle only; expense-row actions are owned by the identity-bound Budget hardening layer.
(()=>{'use strict';
const base=window.PlanlyBudgetUI,money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(n)||0)/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host=null;
function style(){if(document.getElementById('planlyBudgetLifecycleStyle'))return;const s=document.createElement('style');s.id='planlyBudgetLifecycleStyle';s.textContent=`.budgetLifecycleActions{display:flex;align-items:center;justify-content:flex-end;gap:6px;margin-top:7px}.budgetLifecycleBtn{border:1px solid var(--line);border-radius:10px;background:var(--cardSoft);color:var(--text);min-height:30px;padding:0 9px;font-size:10px;font-weight:760}.budgetLifecycleBtn.paid{color:var(--success,#15945f);background:color-mix(in srgb,var(--success,#15945f) 8%,var(--card))}.budgetLifecycleBtn.danger{color:var(--danger,#c43b4d)}.budgetLifecycleOwned{cursor:pointer}.budgetMutationState{font-size:10px;font-weight:760;margin-top:8px}.budgetMutationState.saved{color:var(--success,#15945f)}.budgetMutationState.error{color:var(--danger,#c43b4d)}`;document.head.appendChild(s)}
const api=()=>window.PlanlyBudget,state=()=>api().getState();
async function persistedUpdate(id,patch){const helper=window.PlanlyBudgetActions?.persistedEntryUpdate;if(!helper)throw Error('Budget persistence layer is unavailable.');return helper(id,patch)}
async function persistedDelete(id){const helper=window.PlanlyBudgetActions?.persistedDelete;if(!helper)throw Error('Budget persistence layer is unavailable.');return helper(id)}
function viewChanged(from,to){window.dispatchEvent(new CustomEvent('planly:budget-view-changed',{detail:{from,to}}))}
function currentMonthEntries(){const m=window.PlanlyBudgetActiveMonth||new Date().toISOString().slice(0,7);return state().entries.filter(x=>String(x.entry_date).slice(0,7)===m)}
function dashboard(){const composed=window.PlanlyBudgetUI?.renderTab;if(typeof composed==='function'&&composed!==renderTab)return composed(host);base.showDashboard?.();return base.renderTab(host)}
function canChangeEntry(entry){const s=state(),scope=s.scope,viewer=api().getViewerId?.()||'';return !!entry&&!!scope&&(scope.scope_type==='household'||(scope.scope_type==='personal'&&entry.owner_id===viewer&&scope.owner_id===viewer))}
function decorateIncome(){if(!host)return;const entries=currentMonthEntries().filter(x=>x.kind==='income'),rows=[...host.querySelectorAll('.budgetIncomeRow')];rows.forEach((row,i)=>{const entry=entries[i];if(!entry||row.dataset.lifecycle==='1'||!canChangeEntry(entry))return;row.dataset.lifecycle='1';row.classList.add('budgetLifecycleOwned');row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','Edit '+(entry.description||'income'));row.onclick=()=>edit(entry.id);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();edit(entry.id)}}})}
function status(text,type='saved'){let el=host.querySelector('[data-life-mutation-state]');if(!el){el=document.createElement('div');el.dataset.lifeMutationState='1';el.className='budgetMutationState';host.querySelector('#budgetLifecycleForm')?.appendChild(el)}if(el){el.className='budgetMutationState '+type;el.textContent=text}}
function edit(id){const s=state(),entry=s.entries.find(x=>x.id===id);if(!entry)return dashboard();if(!canChangeEntry(entry)){alert('You cannot edit this payment.');return}viewChanged('income','edit');const cats=s.categories.filter(x=>!x.archived&&x.kind===entry.kind);host.innerHTML=`<button class="budgetBack" data-life-back>‹ Budget</button><section class="budgetCard budgetIncomeCard"><div><strong>Edit income</strong><div class="budgetMuted">Money coming into this budget</div></div><form id="budgetLifecycleForm" class="budgetForm" style="margin-top:16px"><div><label for="lifeName">Source</label><input id="lifeName" maxlength="160" required value="${esc(entry.description||'')}"></div><div><label for="lifeAmount">Amount</label><input id="lifeAmount" type="number" inputmode="decimal" min="0.01" step="0.01" required value="${(Number(entry.amount_minor||0)/100).toFixed(2)}"></div><div><label for="lifeCategory">Income category</label><select id="lifeCategory">${cats.map(c=>`<option value="${esc(c.id)}" ${c.id===entry.category_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><label class="budgetToggle"><input id="lifeRecurring" type="checkbox" ${entry.recurring_monthly?'checked':''}> Repeat monthly</label><button class="budgetBtn budgetPrimary" type="submit">Save changes</button></form><div class="budgetDangerZone"><button type="button" class="budgetBtn" data-life-delete>Delete income</button></div></section>`;host.querySelector('[data-life-back]').onclick=()=>{dashboard();viewChanged('edit','dashboard')};host.querySelector('#budgetLifecycleForm').onsubmit=async e=>{e.preventDefault();const submit=e.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Saving…';try{await persistedUpdate(entry.id,{description:host.querySelector('#lifeName').value,amount_minor:Math.round(Number(host.querySelector('#lifeAmount').value)*100),category_id:host.querySelector('#lifeCategory').value,recurring_monthly:host.querySelector('#lifeRecurring').checked});submit.disabled=false;submit.textContent='Save changes';status('Saved to Budget.')}catch(err){submit.disabled=false;submit.textContent='Save changes';status(err?.message||String(err),'error')}};host.querySelector('[data-life-delete]').onclick=async e=>{if(!confirm('Delete this income?'))return;const b=e.currentTarget;b.disabled=true;b.textContent='Deleting…';try{await persistedDelete(entry.id);b.remove();host.querySelector('#budgetLifecycleForm')?.remove();status('Deleted from Budget.')}catch(err){b.disabled=false;b.textContent='Delete income';status(err?.message||String(err),'error')}}}
function decorate(){decorateIncome()}
async function renderTab(target){style();host=target||host;await base.renderTab(host);queueMicrotask(decorate)}
window.addEventListener('planly:budget-ui-rendered',()=>queueMicrotask(decorateIncome));
window.PlanlyBudgetUI={...base,renderTab};
})();
