// Planly 4.0B.2 — private allocation-first budget cloud/offline runtime.
(()=>{'use strict';
const CACHE='planly-budget-cache-v1:',PENDING='planly-budget-pending-v1:',CONFLICT='planly-budget-conflicts-v1:';
const emptyVersions=()=>({scope:0,categories:{},targets:{},entries:{}}),emptyState=()=>({scope:null,categories:[],targets:[],entries:[],versions:emptyVersions()});
let owner='',sb=null,replayPromise=null,state=emptyState();
const uuid=()=>crypto.randomUUID(),now=()=>Date.now(),minor=n=>Math.max(0,Math.round(Number(n)||0)),key=p=>owner?p+owner:'';
const read=(p,f)=>{const k=key(p);if(!k)return f;try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(p,v)=>{const k=key(p);if(k)localStorage.setItem(k,JSON.stringify(v))};
function normalizeState(raw){const s=raw&&typeof raw==='object'?raw:{};const v=s.versions&&typeof s.versions==='object'?s.versions:{};return {scope:s.scope||null,categories:Array.isArray(s.categories)?s.categories:[],targets:Array.isArray(s.targets)?s.targets:[],entries:Array.isArray(s.entries)?s.entries:[],versions:{scope:Number(v.scope||0),categories:v.categories&&typeof v.categories==='object'?v.categories:{},targets:v.targets&&typeof v.targets==='object'?v.targets:{},entries:v.entries&&typeof v.entries==='object'?v.entries:{}}}}
const persist=()=>write(CACHE,{version:1,savedAt:new Date().toISOString(),state}),restore=()=>{const d=read(CACHE,null);if(d?.version===1&&d.state){state=normalizeState(d.state);return true}return false};
const pending=()=>read(PENDING,[]),conflicts=()=>read(CONFLICT,[]),table=k=>({scope:'planly_budget_scopes',category:'planly_budget_categories',target:'planly_budget_targets',entry:'planly_budget_entries'})[k];
function setVersion(k,id,v){if(!state.versions)state.versions=emptyVersions();if(k==='scope')state.versions.scope=Number(v||0);else{const bucket=k+'s';if(!state.versions[bucket]||typeof state.versions[bucket]!=='object')state.versions[bucket]={};state.versions[bucket][id]=Number(v||0)}}
function stage(kind,action,row,baseVersion){const list=pending().filter(x=>!(x.kind===kind&&x.id===row.id));list.push({kind,action,id:row.id,row:{...row},baseVersion:Number(baseVersion||0),operationId:uuid(),queuedAt:now(),status:'queued'});write(PENDING,list)}
function clearPending(op){write(PENDING,pending().filter(x=>!(x.kind===op.kind&&x.id===op.id&&x.operationId===op.operationId)))}
function clearConflict(k,id){write(CONFLICT,conflicts().filter(x=>!(x.kind===k&&x.id===id)))}
async function fetchRow(k,id){const {data,error}=await sb.from(table(k)).select('*').eq('id',id).maybeSingle();if(error)throw error;return data||null}
function conflict(op,server){const current=pending().find(x=>x.kind===op.kind&&x.id===op.id);if(!current||current.operationId!==op.operationId)return;const list=conflicts().filter(x=>!(x.kind===op.kind&&x.id===op.id));list.push({kind:op.kind,id:op.id,local:op.row,server,baseVersion:op.baseVersion,recordedAt:now()});write(CONFLICT,list);current.status='conflict';write(PENDING,pending().map(x=>x.kind===op.kind&&x.id===op.id&&x.operationId===op.operationId?current:x))}
function clean(row){const r={...row};delete r.cloud_version;delete r.created_at;delete r.updated_at;return r}
function sameInsert(op,server){return !!server&&op.baseVersion===0&&server.id===op.id&&server.client_id&&server.client_id===op.row.client_id&&server.owner_id===op.row.owner_id}
function acceptServer(op,server){setVersion(op.kind,op.id,server.cloud_version);clearPending(op);clearConflict(op.kind,op.id)}
async function push(op){const r=clean(op.row);if(op.action==='delete')r.deleted_at=new Date().toISOString();let res;if(op.baseVersion)res=await sb.from(table(op.kind)).update(r).eq('id',op.id).eq('cloud_version',op.baseVersion).select('*').maybeSingle();else res=await sb.from(table(op.kind)).insert(r).select('*').single();if(res.error){if(!op.baseVersion){const server=await fetchRow(op.kind,op.id).catch(()=>null);if(sameInsert(op,server)){acceptServer(op,server);return true}if(server){conflict(op,server);return false}}throw res.error}if(op.baseVersion&&!res.data){conflict(op,await fetchRow(op.kind,op.id));return false}acceptServer(op,res.data);return true}
async function reconcileInsertJournal(){for(const op of pending().filter(x=>x.baseVersion===0)){const server=await fetchRow(op.kind,op.id).catch(()=>null);if(sameInsert(op,server))acceptServer(op,server)}}
async function replayNow(){if(!navigator.onLine||!owner||!sb)return;await reconcileInsertJournal();for(const op of pending().filter(x=>x.status!=='conflict')){try{await push(op)}catch(e){if(!navigator.onLine)break;console.warn('Planly budget sync',e)}}persist()}
function replay(){if(replayPromise)return replayPromise;replayPromise=replayNow().finally(()=>{replayPromise=null;if(navigator.onLine&&owner&&sb&&pending().some(x=>x.status!=='conflict'))queueMicrotask(()=>replay())});return replayPromise}
async function bootstrap(){if(!owner||!sb)return false;restore();if(!navigator.onLine)return true;let {data:scopes,error}=await sb.from('planly_budget_scopes').select('*').eq('owner_id',owner).eq('scope_type','personal').is('deleted_at',null);if(error)throw error;let scope=scopes?.[0]||null;if(!scope){const row={id:uuid(),owner_id:owner,household_id:null,scope_type:'personal',name:'Personal Budget',currency:'GBP',client_id:'personal-'+uuid(),client_created_at:now(),client_updated_at:now(),deleted_at:null};stage('scope','upsert',row,0);await replay();scope=await fetchRow('scope',row.id)}state.scope=scope;if(!scope)return false;setVersion('scope',scope.id,scope.cloud_version);const results=await Promise.all(['planly_budget_categories','planly_budget_targets','planly_budget_entries'].map(t=>sb.from(t).select('*').eq('scope_id',scope.id).is('deleted_at',null)));for(const r of results)if(r.error)throw r.error;[state.categories,state.targets,state.entries]=results.map(r=>r.data||[]);for(const x of state.categories)setVersion('category',x.id,x.cloud_version);for(const x of state.targets)setVersion('target',x.id,x.cloud_version);for(const x of state.entries)setVersion('entry',x.id,x.cloud_version);await reconcileInsertJournal();persist();await replay();return true}
function addCategory({name,kind='expense',iconKey='wallet',colorKey='violet'}){if(!state.scope)throw Error('Budget is not ready.');const t=String(name||'').trim();if(!t)throw Error('Category name is required.');const row={id:uuid(),scope_id:state.scope.id,owner_id:owner,client_id:'category-'+uuid(),name:t.slice(0,80),kind,icon_key:String(iconKey||'wallet').slice(0,32),color_key:String(colorKey||'violet').slice(0,24),sort_order:state.categories.length,archived:false,client_created_at:now(),client_updated_at:now(),deleted_at:null};state.categories.push(row);stage('category','upsert',row,0);persist();replay();return row}
function addEntry({kind='expense',amountMinor,categoryId,entryDate,description='',notes='',allocationStatus='planned',dueDay=null,recurringMonthly=true}){if(!state.scope)throw Error('Budget is not ready.');const cat=state.categories.find(x=>x.id===categoryId&&!x.archived);if(!cat||cat.kind!==kind)throw Error('Choose a matching budget category.');const row={id:uuid(),scope_id:state.scope.id,category_id:cat.id,owner_id:owner,client_id:'entry-'+uuid(),kind,amount_minor:minor(amountMinor),entry_date:entryDate||new Date().toISOString().slice(0,10),description:String(description).slice(0,160),notes:String(notes).slice(0,500),allocation_status:allocationStatus==='paid'?'paid':'planned',due_day:dueDay?Math.min(31,Math.max(1,Number(dueDay))):null,recurring_monthly:recurringMonthly!==false,client_created_at:now(),client_updated_at:now(),deleted_at:null};state.entries.unshift(row);stage('entry','upsert',row,0);persist();replay();return row}
function updateEntry(id,patch){const row=state.entries.find(x=>x.id===id);if(!row)throw Error('Budget allocation not found.');const next={...patch};delete next.owner_id;delete next.scope_id;delete next.client_id;delete next.id;Object.assign(row,next,{client_updated_at:now()});stage('entry','upsert',row,state.versions.entries[id]||0);persist();replay();return row}
function updateCategory(id,patch){const row=state.categories.find(x=>x.id===id);if(!row)throw Error('Budget category not found.');const next={...patch};delete next.owner_id;delete next.scope_id;delete next.client_id;delete next.id;Object.assign(row,next,{client_updated_at:now()});stage('category','upsert',row,state.versions.categories[id]||0);persist();replay();return row}
function deleteEntry(id){const row=state.entries.find(x=>x.id===id);if(!row)return;state.entries=state.entries.filter(x=>x.id!==id);stage('entry','delete',row,state.versions.entries[id]||0);persist();replay()}
function setTarget({categoryId,budgetMonth,amountMinor}){let row=state.targets.find(x=>x.category_id===categoryId&&x.budget_month===budgetMonth);if(!row){row={id:uuid(),scope_id:state.scope.id,category_id:categoryId,owner_id:owner,client_id:'target-'+uuid(),budget_month:budgetMonth,amount_minor:minor(amountMinor),client_created_at:now(),client_updated_at:now(),deleted_at:null};state.targets.push(row);stage('target','upsert',row,0)}else{row.amount_minor=minor(amountMinor);row.client_updated_at=now();stage('target','upsert',row,state.versions.targets[row.id]||0)}persist();replay();return row}
function summary(month=new Date().toISOString().slice(0,7)){const rows=state.entries.filter(x=>String(x.entry_date).slice(0,7)===month),income=rows.filter(x=>x.kind==='income').reduce((s,x)=>s+Number(x.amount_minor),0),expense=rows.filter(x=>x.kind==='expense').reduce((s,x)=>s+Number(x.amount_minor),0);return {month,income,expense,balance:income-expense,entries:rows.length}}
async function init(){if(!window.supabase?.createClient||!window.PLANLY_SUPABASE_CONFIG)return;sb=window.supabase.createClient(PLANLY_SUPABASE_CONFIG.url,PLANLY_SUPABASE_CONFIG.publishableKey);const {data}=await sb.auth.getSession();owner=data.session?.user?.id||'';if(owner)await bootstrap();sb.auth.onAuthStateChange((_e,s)=>{const next=s?.user?.id||'';if(next!==owner){owner=next;replayPromise=null;state=emptyState();if(owner)bootstrap().catch(console.warn)}})}
window.PlanlyBudget={bootstrap,replay,restore,addCategory,updateCategory,addEntry,updateEntry,deleteEntry,setTarget,summary,getState:()=>structuredClone(state),getPending:pending,getConflicts:conflicts};
window.addEventListener('online',()=>replay());setTimeout(()=>init().catch(e=>console.warn('Planly budget init',e)),0);
})();
