(()=>{
'use strict';
const STATUS_PREFIX='planly-cloud-migration-status-v1:';
const LAST_ACCOUNT_KEY='planly-cloud-last-account-v1';
const WRITABLE_STATES=new Set(['cloud-write-test','offline-retry-needed','conflict']);
let refreshTimer=0,lastForegroundKick=0,realtimeClient=null,realtimeChannel=null,realtimeHouseholdId='',realtimeArmPromise=null;
let assignmentClient=null,assignmentContext={householdId:'',userId:'',members:[],labels:new Map()},assignmentLoadPromise=null,pendingAssignment=null,authSyncBound=false,assignmentHydratePromise=null;
function cloudStatus(){const ownerId=String(localStorage.getItem(LAST_ACCOUNT_KEY)||'');if(!ownerId)return {};try{return JSON.parse(localStorage.getItem(STATUS_PREFIX+ownerId)||'{}')||{}}catch{return {}}}
function householdWritesReady(){return WRITABLE_STATES.has(String(cloudStatus().state||''))}
function clientForAssignment(){if(assignmentClient)return assignmentClient;const cfg=window.PLANLY_SUPABASE_CONFIG;if(!window.supabase?.createClient||!cfg?.url||!cfg?.publishableKey)return null;assignmentClient=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:false,detectSessionInUrl:false}});return assignmentClient}
async function loadAssignmentContext(force=false){if(assignmentLoadPromise&&!force)return assignmentLoadPromise;assignmentLoadPromise=(async()=>{const client=clientForAssignment();if(!client)return assignmentContext;const {data:{session}={}}=await client.auth.getSession();const userId=String(session?.user?.id||'');if(!userId){assignmentContext={householdId:'',userId:'',members:[],labels:new Map()};return assignmentContext}const {data:mine,error:mineError}=await client.from('planly_household_members').select('household_id,user_id,role,joined_at').eq('user_id',userId).limit(1);if(mineError||!mine?.[0]){assignmentContext={householdId:'',userId,members:[],labels:new Map()};return assignmentContext}const householdId=String(mine[0].household_id);const {data:members,error:memberError}=await client.from('planly_household_members').select('household_id,user_id,role,joined_at').eq('household_id',householdId).order('joined_at',{ascending:true});if(memberError)throw memberError;const labels=new Map([[userId,'You']]);try{const {data:invites}=await client.from('planly_household_invites').select('invited_email,accepted_by,status').eq('household_id',householdId).eq('status','accepted');for(const invite of invites||[])if(invite.accepted_by&&invite.invited_email)labels.set(String(invite.accepted_by),String(invite.invited_email))}catch{}for(const member of members||[]){const id=String(member.user_id);if(labels.has(id))continue;labels.set(id,member.role==='owner'?'Household owner':'Household member')}assignmentContext={householdId,userId,members:members||[],labels};return assignmentContext})().catch(()=>assignmentContext).finally(()=>{assignmentLoadPromise=null});return assignmentLoadPromise}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureAssignmentField(){const visibility=document.getElementById('taskVisibility');if(!visibility)return null;let wrap=document.getElementById('taskAssigneeField');if(!wrap){wrap=document.createElement('div');wrap.id='taskAssigneeField';wrap.className='field taskAssigneeField';wrap.hidden=true;wrap.innerHTML='<label for="taskAssignee">Assign to</label><select id="taskAssignee" class="select"><option value="">Anyone in household</option></select><div class="fieldHint">Assignment shows who is responsible. The task creator still owns editing and deletion.</div>';visibility.closest('.taskSharingField')?.insertAdjacentElement('afterend',wrap)}return wrap}
async function refreshAssignmentField({loadTask=true}={}){const visibility=document.getElementById('taskVisibility'),wrap=ensureAssignmentField(),select=document.getElementById('taskAssignee');if(!visibility||!wrap||!select)return;const shared=visibility.value==='household';wrap.hidden=!shared;if(!shared){select.value='';return}const ctx=await loadAssignmentContext();const current=select.value;select.innerHTML='<option value="">Anyone in household</option>'+ctx.members.map(m=>'<option value="'+String(m.user_id).replace(/"/g,'&quot;')+'">'+escapeHtml(ctx.labels.get(String(m.user_id))||'Household member')+'</option>').join('');if(current&&ctx.members.some(m=>String(m.user_id)===current))select.value=current;if(loadTask){const taskId=String(document.getElementById('taskId')?.value||'');if(taskId){const client=clientForAssignment();const {data}=await client.from('planly_tasks').select('assignee_id').eq('owner_id',ctx.userId).eq('client_id',taskId).maybeSingle();if(data?.assignee_id&&ctx.members.some(m=>String(m.user_id)===String(data.assignee_id)))select.value=String(data.assignee_id);else select.value=''}else select.value=''}}
function refreshSharingGate(){const select=document.getElementById('taskVisibility');if(!select)return;const option=[...select.options].find(o=>o.value==='household');if(!option)return;const ready=householdWritesReady();option.disabled=!ready;const editingShared=!!document.getElementById('taskId')?.value&&select.value==='household';if(!ready&&select.value==='household'&&!editingShared)select.value='private';const help=document.getElementById('taskVisibilityHelp');if(help&&!ready)help.textContent='Household sharing becomes available once Planly Cloud Sync is active. This prevents a task looking shared before it can be safely synced.';void refreshAssignmentField({loadTask:false});void hydrateIncomingAssignments()}
function scheduleGateRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshSharingGate,0)}
function kickHouseholdSync(){if(!navigator.onLine)return;window.dispatchEvent(new Event('online'));setTimeout(scheduleGateRefresh,250)}
function kickForegroundHouseholdSync(){if(!navigator.onLine)return;const now=Date.now();if(now-lastForegroundKick<1200)return;lastForegroundKick=now;kickHouseholdSync();void armHouseholdRealtime()}
async function stopHouseholdRealtime(){const client=realtimeClient,channel=realtimeChannel;realtimeChannel=null;realtimeHouseholdId='';if(client&&channel){try{await client.removeChannel(channel)}catch{}}}
async function armHouseholdRealtime(){if(realtimeArmPromise)return realtimeArmPromise;realtimeArmPromise=(async()=>{if(!navigator.onLine||!window.supabase?.createClient||!window.PLANLY_SUPABASE_CONFIG)return;const cfg=window.PLANLY_SUPABASE_CONFIG;if(!realtimeClient)realtimeClient=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:false,detectSessionInUrl:false}});const {data:{session}={},error:sessionError}=await realtimeClient.auth.getSession();if(sessionError||!session?.access_token){await stopHouseholdRealtime();return}const ownerId=String(localStorage.getItem(LAST_ACCOUNT_KEY)||'');if(!ownerId||ownerId!==String(session.user?.id||'')){await stopHouseholdRealtime();return}const {data:memberships,error:membershipError}=await realtimeClient.from('planly_household_members').select('household_id').eq('user_id',session.user.id).limit(1);if(membershipError||!memberships?.[0]?.household_id){await stopHouseholdRealtime();return}const householdId=String(memberships[0].household_id);if(realtimeChannel&&realtimeHouseholdId===householdId)return;await stopHouseholdRealtime();await realtimeClient.realtime.setAuth(session.access_token);realtimeHouseholdId=householdId;realtimeChannel=realtimeClient.channel(`household:${householdId}`,{config:{private:true}}).on('broadcast',{event:'*'},()=>kickHouseholdSync()).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){if(realtimeChannel){void realtimeClient.removeChannel(realtimeChannel).catch(()=>{});realtimeChannel=null;realtimeHouseholdId=''}}})})().catch(()=>{}).finally(()=>{realtimeArmPromise=null});return realtimeArmPromise}
async function applyPendingAssignment(){const p=pendingAssignment;pendingAssignment=null;if(!p||p.visibility!=='household')return;const client=clientForAssignment(),ctx=await loadAssignmentContext();if(!client||!ctx.userId||!ctx.householdId)return;let row=null;for(let attempt=0;attempt<8&&!row;attempt++){if(attempt)await new Promise(r=>setTimeout(r,350));let q=client.from('planly_tasks').select('owner_id,client_id,data,assignee_id,household_id,visibility,client_updated_at').eq('owner_id',ctx.userId).eq('visibility','household').is('deleted_at',null);if(p.taskId)q=q.eq('client_id',p.taskId);else{q=q.eq('title',p.title);if(p.date)q=q.eq('task_date',p.date);q=q.order('client_updated_at',{ascending:false}).limit(1)}const {data,error}=await q.maybeSingle();if(!error&&data)row=data}if(!row)return;const assigneeId=p.assigneeId||null;const nextData={...(row.data||{}),visibility:'household',householdId:ctx.householdId};if(assigneeId)nextData.assigneeId=assigneeId;else delete nextData.assigneeId;const {error}=await client.from('planly_tasks').update({assignee_id:assigneeId,data:nextData,client_updated_at:Date.now()}).eq('owner_id',ctx.userId).eq('client_id',row.client_id);if(error){console.warn('Planly assignment update failed',error);return}kickHouseholdSync()}
function taskForCard(card){const id=String(card?.dataset?.id||''),owner=String(card?.dataset?.owner||'');if(!id||typeof state==='undefined')return null;return state.tasks.find(t=>String(t.id)===id&&String(t._planlyOwnerId||planlySession?.user?.id||'')===owner)||null}
function assignedToCurrentUser(task,ctx=assignmentContext){return !!task&&task.visibility==='household'&&task._planlyOwnedByMe===false&&String(task.assigneeId||'')===String(ctx.userId||'')}
async function hydrateIncomingAssignments(){if(assignmentHydratePromise)return assignmentHydratePromise;assignmentHydratePromise=(async()=>{if(typeof state==='undefined'||!Array.isArray(state.tasks))return;const client=clientForAssignment(),ctx=await loadAssignmentContext();if(!client||!ctx.userId||!ctx.householdId)return;const incoming=state.tasks.filter(t=>t&&t.visibility==='household'&&t._planlyOwnedByMe===false&&t.id&&t._planlyOwnerId);if(!incoming.length){void decorateAssignments();return}const owners=[...new Set(incoming.map(t=>String(t._planlyOwnerId)).filter(Boolean))];const ids=[...new Set(incoming.map(t=>String(t.id)).filter(Boolean))];if(!owners.length||!ids.length)return;const {data:rows,error}=await client.from('planly_tasks').select('owner_id,client_id,assignee_id').eq('household_id',ctx.householdId).eq('visibility','household').is('deleted_at',null).in('owner_id',owners).in('client_id',ids);if(error){console.warn('Planly assignment hydration failed',error);return}const byKey=new Map((rows||[]).map(r=>[String(r.owner_id)+'::'+String(r.client_id),r.assignee_id?String(r.assignee_id):'']));let changed=false;for(const task of incoming){const key=String(task._planlyOwnerId)+'::'+String(task.id);if(!byKey.has(key))continue;const next=byKey.get(key);if(String(task.assigneeId||'')!==next){if(next)task.assigneeId=next;else delete task.assigneeId;changed=true}}if(changed&&typeof render==='function')render();else void decorateAssignments()})().catch(err=>console.warn('Planly assignment hydration failed',err)).finally(()=>{assignmentHydratePromise=null});return assignmentHydratePromise}
async function setAssignedTaskCompleted(task,completed){const client=clientForAssignment(),ctx=await loadAssignmentContext();if(!client||!assignedToCurrentUser(task,ctx))return false;const ownerId=String(task._planlyOwnerId||'');if(!ownerId)return false;const {error}=await client.rpc('planly_set_assigned_task_completed',{p_owner_id:ownerId,p_client_id:String(task.id),p_completed:!!completed});if(error){console.warn('Planly assignee completion failed',error);alert('Planly could not update this assigned task. Please try again.');return false}task.completed=!!completed;task.updatedAt=Date.now();render();kickHouseholdSync();return true}
async function decorateAssignments(){let ctx;try{ctx=await loadAssignmentContext()}catch{return}if(!ctx?.userId)return;document.querySelectorAll('.task[data-id]').forEach(card=>{const task=taskForCard(card),meta=card.querySelector('.meta');if(!task||!meta)return;const existing=meta.querySelector('.taskAssigneePill'),assigneeId=String(task.assigneeId||'');if(!assigneeId){if(existing)existing.remove()}else{const label='✓ '+(assigneeId===ctx.userId?'Assigned to you':'Assigned to '+(ctx.labels.get(assigneeId)||'household member'));if(existing?.textContent!==label){if(existing)existing.textContent=label;else{const pill=document.createElement('span');pill.className='pill taskAssigneePill';pill.textContent=label;meta.appendChild(pill)}}}const check=card.querySelector('.check');const mine=assignedToCurrentUser(task,ctx);if(check&&mine){check.disabled=false;check.dataset.assigneeToggle='true';check.setAttribute('aria-label',task.completed?'Mark assigned task incomplete':'Complete assigned task');card.classList.add('assignedToMeTask');const mark=card.querySelector('.sharedReadOnlyMark');if(mark&&mark.textContent!=='Assigned to you')mark.textContent='Assigned to you'}else if(check){delete check.dataset.assigneeToggle;card.classList.remove('assignedToMeTask')}})}
function installAssignmentStyle(){if(document.getElementById('planlyAssignmentPolish'))return;const style=document.createElement('style');style.id='planlyAssignmentPolish';style.textContent='.taskAssigneePill{font-weight:750;white-space:normal;overflow-wrap:anywhere}.taskAssigneeField select{overflow-wrap:normal;word-break:normal}.taskAssigneeField option{word-break:normal}.assignedToMeTask .check:not(:disabled){cursor:pointer}.assignedToMeTask .sharedReadOnlyMark{color:var(--accent);font-weight:750}';document.head.appendChild(style)}
function bindPostLoginSync(){if(authSyncBound)return;const client=clientForAssignment();if(!client)return;authSyncBound=true;client.auth.onAuthStateChange((event,session)=>{if(!session?.user)return;assignmentContext={householdId:'',userId:String(session.user.id),members:[],labels:new Map()};setTimeout(()=>{void loadAssignmentContext(true).then(()=>{kickHouseholdSync();void armHouseholdRealtime();void hydrateIncomingAssignments()})},150);setTimeout(()=>{kickHouseholdSync();void hydrateIncomingAssignments()},900)})}
document.addEventListener('submit',e=>{if(e.target?.id!=='taskForm')return;const visibility=document.getElementById('taskVisibility');if(visibility?.value==='household'&&!householdWritesReady()){e.preventDefault();e.stopImmediatePropagation();alert('Household sharing is not ready yet. Enable Planly Cloud Sync in Settings, then save the task again.');scheduleGateRefresh();return}pendingAssignment={taskId:String(document.getElementById('taskId')?.value||''),title:String(document.getElementById('taskTitle')?.value||'').trim(),date:String(document.getElementById('taskDate')?.value||''),visibility:visibility?.value||'private',assigneeId:String(document.getElementById('taskAssignee')?.value||'')};setTimeout(()=>void applyPendingAssignment(),80)},true);
document.addEventListener('change',e=>{if(e.target?.id!=='taskVisibility')return;if(e.target.value==='household'&&!householdWritesReady()){e.target.value='private';alert('Enable Planly Cloud Sync in Settings before sharing a task with your household.')}void refreshAssignmentField({loadTask:false});scheduleGateRefresh()},true);
document.addEventListener('click',e=>{const assignedToggle=e.target.closest('.check[data-assignee-toggle="true"]');if(assignedToggle){const card=assignedToggle.closest('.task[data-id]'),task=taskForCard(card);if(task&&assignedToCurrentUser(task)){e.preventDefault();e.stopImmediatePropagation();void setAssignedTaskCompleted(task,!task.completed)}return}if(e.target.closest('#addBtn'))setTimeout(()=>void refreshAssignmentField({loadTask:false}),20);if(e.target.closest('[data-action="edit"]'))setTimeout(()=>void refreshAssignmentField({loadTask:true}),80);if(e.target.closest('#duplicateTask'))setTimeout(()=>{const a=document.getElementById('taskAssignee');if(a)a.value='';void refreshAssignmentField({loadTask:false})},20)},true);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){kickForegroundHouseholdSync();setTimeout(()=>void hydrateIncomingAssignments(),300)}});
window.addEventListener('focus',()=>{kickForegroundHouseholdSync();setTimeout(()=>void hydrateIncomingAssignments(),300)});
window.addEventListener('online',()=>{setTimeout(scheduleGateRefresh,300);setTimeout(()=>void armHouseholdRealtime(),350);setTimeout(()=>void hydrateIncomingAssignments(),500)});
window.addEventListener('pagehide',()=>void stopHouseholdRealtime());
let mutationHydrateTimer=0;new MutationObserver(()=>{scheduleGateRefresh();clearTimeout(mutationHydrateTimer);mutationHydrateTimer=setTimeout(()=>void hydrateIncomingAssignments(),120)}).observe(document.documentElement,{subtree:true,childList:true});
installAssignmentStyle();bindPostLoginSync();refreshSharingGate();setTimeout(()=>{void loadAssignmentContext(true).then(()=>void hydrateIncomingAssignments());void armHouseholdRealtime()},500);
})();