(()=>{
'use strict';
const STATUS_PREFIX='planly-cloud-migration-status-v1:';
const LAST_ACCOUNT_KEY='planly-cloud-last-account-v1';
const WRITABLE_STATES=new Set(['cloud-write-test','offline-retry-needed','conflict']);
let refreshTimer=0,lastForegroundKick=0,realtimeClient=null,realtimeChannel=null,realtimeHouseholdId='',realtimeArmPromise=null;
let assignmentClient=null,assignmentContext={householdId:'',userId:'',members:[],labels:new Map()},assignmentContextLoadedAt=0,assignmentLoadPromise=null,pendingAssignment=null,authSyncBound=false;
const ASSIGNMENT_CONTEXT_TTL_MS=60000;
function cloudStatus(){const ownerId=String(localStorage.getItem(LAST_ACCOUNT_KEY)||'');if(!ownerId)return {};try{return JSON.parse(localStorage.getItem(STATUS_PREFIX+ownerId)||'{}')||{}}catch{return {}}}
function householdWritesReady(){return WRITABLE_STATES.has(String(cloudStatus().state||''))}
function clientForAssignment(){if(assignmentClient)return assignmentClient;const cfg=window.PLANLY_SUPABASE_CONFIG;if(!window.supabase?.createClient||!cfg?.url||!cfg?.publishableKey)return null;assignmentClient=window.PlanlySupabase?.get?.();return assignmentClient}
async function loadAssignmentContext(force=false){const client=clientForAssignment();if(!client)return assignmentContext;const {data:{session}={}}=await client.auth.getSession();const userId=String(session?.user?.id||'');if(!userId){assignmentContext={householdId:'',userId:'',members:[],labels:new Map()};assignmentContextLoadedAt=Date.now();return assignmentContext}const shared=window.PlanlyHouseholdContext;if(shared&&String(shared.userId||'')===userId){const members=Array.isArray(shared.members)?shared.members:[],labels=new Map([[userId,'You']]);for(const invite of Array.isArray(shared.acceptedInvites)?shared.acceptedInvites:[])if(invite.accepted_by&&invite.invited_email)labels.set(String(invite.accepted_by),String(invite.invited_email));for(const member of members){const id=String(member.user_id||''),name=String(member.display_name||'').trim();if(!id)continue;if(name){labels.set(id,name);continue}if(labels.has(id))continue;labels.set(id,id===userId?'You':member.role==='owner'?'Household owner':'Household member')}assignmentContext={householdId:String(shared.householdId||''),userId,members,labels};assignmentContextLoadedAt=Date.now();return assignmentContext}assignmentContext={householdId:'',userId,members:[],labels:new Map()};assignmentContextLoadedAt=0;return assignmentContext}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureAssignmentField(){const visibility=document.getElementById('taskVisibility');if(!visibility)return null;let wrap=document.getElementById('taskAssigneeField');if(!wrap){wrap=document.createElement('div');wrap.id='taskAssigneeField';wrap.className='field taskAssigneeField';wrap.hidden=true;wrap.innerHTML='<label>Assign</label><div id="taskAssigneeSegments" class="taskChoiceSegments" role="group" aria-label="Assign task"></div><select id="taskAssignee" class="select taskChoiceBacking" aria-hidden="true" tabindex="-1"><option value="">Anyone</option></select><div class="fieldHint">Assignment shows who is responsible. The task creator still owns editing and deletion.</div>';visibility.closest('.taskSharingField')?.insertAdjacentElement('afterend',wrap)}return wrap}
function syncTaskChoiceButtons(){const visibility=document.getElementById('taskVisibility');document.querySelectorAll('[data-task-visibility]').forEach(btn=>{btn.classList.toggle('active',btn.dataset.taskVisibility===visibility?.value);btn.setAttribute('aria-pressed',btn.classList.contains('active')?'true':'false')});const assignee=document.getElementById('taskAssignee');document.querySelectorAll('[data-task-assignee]').forEach(btn=>{btn.classList.toggle('active',btn.dataset.taskAssignee===(assignee?.value||''));btn.setAttribute('aria-pressed',btn.classList.contains('active')?'true':'false')})}
async function refreshAssignmentField({loadTask=true}={}){const visibility=document.getElementById('taskVisibility'),host=document.getElementById('taskHouseholdControls'),wrap=ensureAssignmentField(),select=document.getElementById('taskAssignee');if(!visibility||!wrap||!select)return;const ctx=await loadAssignmentContext();if(host)host.hidden=!ctx.householdId;const shared=visibility.value==='household';wrap.hidden=!shared||!ctx.householdId;if(!shared){select.value='';syncTaskChoiceButtons();return}const current=select.value;select.innerHTML='<option value="">Anyone</option>'+ctx.members.map(m=>'<option value="'+String(m.user_id).replace(/"/g,'&quot;')+'">'+escapeHtml(ctx.labels.get(String(m.user_id))||'Household member')+'</option>').join('');if(current&&ctx.members.some(m=>String(m.user_id)===current))select.value=current;if(loadTask){const taskId=String(document.getElementById('taskId')?.value||'');if(taskId){const client=clientForAssignment();const {data}=await client.from('planly_tasks').select('assignee_id').eq('owner_id',ctx.userId).eq('client_id',taskId).maybeSingle();if(data?.assignee_id&&ctx.members.some(m=>String(m.user_id)===String(data.assignee_id)))select.value=String(data.assignee_id);else select.value=''}else select.value=''}const segments=document.getElementById('taskAssigneeSegments');if(segments)segments.innerHTML=[['','Anyone'],...ctx.members.map(m=>[String(m.user_id),ctx.labels.get(String(m.user_id))||'Household member'])].map(([id,label])=>'<button type="button" data-task-assignee="'+String(id).replace(/"/g,'&quot;')+'">'+escapeHtml(label)+'</button>').join('');syncTaskChoiceButtons()}
function refreshSharingGate(){const select=document.getElementById('taskVisibility');if(!select)return;const option=[...select.options].find(o=>o.value==='household');if(!option)return;const ready=householdWritesReady();option.disabled=!ready;const editingShared=!!document.getElementById('taskId')?.value&&select.value==='household';if(!ready&&select.value==='household'&&!editingShared)select.value='private';const help=document.getElementById('taskVisibilityHelp');if(help&&!ready)help.textContent='Household sharing becomes available once Planly Cloud Sync is active. This prevents a task looking shared before it can be safely synced.';void refreshAssignmentField({loadTask:false});}
function scheduleGateRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshSharingGate,0)}
function kickHouseholdSync(){if(!navigator.onLine)return;setTimeout(scheduleGateRefresh,0);window.dispatchEvent(new CustomEvent('planly:household-remote-change'));void armHouseholdRealtime()}
function kickForegroundHouseholdSync(){if(!navigator.onLine)return;const now=Date.now();if(now-lastForegroundKick<1200)return;lastForegroundKick=now;setTimeout(scheduleGateRefresh,0);void armHouseholdRealtime()}
async function stopHouseholdRealtime(){const client=realtimeClient,channel=realtimeChannel;realtimeChannel=null;realtimeHouseholdId='';if(client&&channel){try{await client.removeChannel(channel)}catch{}}}
async function armHouseholdRealtime(){if(realtimeArmPromise)return realtimeArmPromise;if(realtimeChannel&&realtimeHouseholdId)return;realtimeArmPromise=(async()=>{if(!navigator.onLine||!window.supabase?.createClient||!window.PLANLY_SUPABASE_CONFIG)return;const cfg=window.PLANLY_SUPABASE_CONFIG;if(!realtimeClient)realtimeClient=window.PlanlySupabase?.get?.();const {data:{session}={},error:sessionError}=await realtimeClient.auth.getSession();if(sessionError||!session?.access_token){await stopHouseholdRealtime();return}const ownerId=String(localStorage.getItem(LAST_ACCOUNT_KEY)||'');if(!ownerId||ownerId!==String(session.user?.id||'')){await stopHouseholdRealtime();return}const ctx=await loadAssignmentContext(false);if(!ctx?.householdId||String(ctx.userId)!==String(session.user.id)){await stopHouseholdRealtime();return}const householdId=String(ctx.householdId);if(realtimeChannel&&realtimeHouseholdId===householdId)return;await stopHouseholdRealtime();await realtimeClient.realtime.setAuth(session.access_token);realtimeHouseholdId=householdId;realtimeChannel=realtimeClient.channel(`household:${householdId}`,{config:{private:true}}).on('broadcast',{event:'*'},()=>kickHouseholdSync()).subscribe(status=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){if(realtimeChannel){void realtimeClient.removeChannel(realtimeChannel).catch(()=>{});realtimeChannel=null;realtimeHouseholdId=''}}})})().catch(()=>{}).finally(()=>{realtimeArmPromise=null});return realtimeArmPromise}
async function applyPendingAssignment(){const p=pendingAssignment;pendingAssignment=null;if(!p||p.visibility!=='household')return;const client=clientForAssignment(),ctx=await loadAssignmentContext();if(!client||!ctx.userId||!ctx.householdId)return;let row=null;for(let attempt=0;attempt<8&&!row;attempt++){if(attempt)await new Promise(r=>setTimeout(r,350));let q=client.from('planly_tasks').select('owner_id,client_id,data,assignee_id,household_id,visibility,client_updated_at').eq('owner_id',ctx.userId).eq('visibility','household').is('deleted_at',null);if(p.taskId)q=q.eq('client_id',p.taskId);else{q=q.eq('title',p.title);if(p.date)q=q.eq('task_date',p.date);q=q.order('client_updated_at',{ascending:false}).limit(1)}const {data,error}=await q.maybeSingle();if(!error&&data)row=data}if(!row)return;const assigneeId=p.assigneeId||null;const nextData={...(row.data||{}),visibility:'household',householdId:ctx.householdId};if(assigneeId)nextData.assigneeId=assigneeId;else delete nextData.assigneeId;const {error}=await client.from('planly_tasks').update({assignee_id:assigneeId,data:nextData,client_updated_at:Date.now()}).eq('owner_id',ctx.userId).eq('client_id',row.client_id);if(error){console.warn('Planly assignment update failed',error);return}kickHouseholdSync()}
function installAssignmentStyle(){if(document.getElementById('planlyAssignmentPolish'))return;const style=document.createElement('style');style.id='planlyAssignmentPolish';style.textContent='.taskAssigneePill{font-weight:750;white-space:normal;overflow-wrap:anywhere}.taskAssigneeField select{overflow-wrap:normal;word-break:normal}.taskAssigneeField option{word-break:normal}.assignedToMeTask .check:not(:disabled){cursor:pointer}.assignedToMeTask .sharedReadOnlyMark{color:var(--accent);font-weight:750}';document.head.appendChild(style)}
function bindPostLoginSync(){if(authSyncBound)return;const client=clientForAssignment();if(!client)return;authSyncBound=true;let authUserId='';client.auth.onAuthStateChange((event,session)=>{const userId=String(session?.user?.id||'');if(!userId){authUserId='';return}if(userId===authUserId)return;authUserId=userId;assignmentContext={householdId:'',userId,members:[],labels:new Map()};assignmentContextLoadedAt=0;setTimeout(()=>{void loadAssignmentContext(false).then(()=>{kickHouseholdSync();void armHouseholdRealtime();})},150)})}
document.addEventListener('submit',e=>{if(e.target?.id!=='taskForm')return;const visibility=document.getElementById('taskVisibility');if(visibility?.value==='household'&&!householdWritesReady()){e.preventDefault();e.stopImmediatePropagation();alert('Household sharing is not ready yet. Enable Planly Cloud Sync in Settings, then save the task again.');scheduleGateRefresh();return}pendingAssignment={taskId:String(document.getElementById('taskId')?.value||''),title:String(document.getElementById('taskTitle')?.value||'').trim(),date:String(document.getElementById('taskDate')?.value||''),visibility:visibility?.value||'private',assigneeId:String(document.getElementById('taskAssignee')?.value||'')};setTimeout(()=>void applyPendingAssignment(),80)},true);
document.addEventListener('change',e=>{if(e.target?.id!=='taskVisibility')return;if(e.target.value==='household'&&!householdWritesReady()){e.target.value='private';alert('Enable Planly Cloud Sync in Settings before sharing a task with your household.')}void refreshAssignmentField({loadTask:false});scheduleGateRefresh()},true);
document.addEventListener('click',e=>{const visibilityChoice=e.target.closest('[data-task-visibility]');if(visibilityChoice){const select=document.getElementById('taskVisibility');if(!select)return;if(visibilityChoice.dataset.taskVisibility==='household'&&!householdWritesReady()){alert('Enable Planly Cloud Sync in Settings before sharing a task with your household.');return}select.value=visibilityChoice.dataset.taskVisibility;select.dispatchEvent(new Event('change',{bubbles:true}));syncTaskChoiceButtons();return}const assigneeChoice=e.target.closest('[data-task-assignee]');if(assigneeChoice){const select=document.getElementById('taskAssignee');if(select){select.value=assigneeChoice.dataset.taskAssignee||'';syncTaskChoiceButtons()}return}if(e.target.closest('#addBtn'))setTimeout(()=>void refreshAssignmentField({loadTask:false}),20);if(e.target.closest('[data-action="edit"]'))setTimeout(()=>void refreshAssignmentField({loadTask:true}),80);if(e.target.closest('#duplicateTask'))setTimeout(()=>{const a=document.getElementById('taskAssignee');if(a)a.value='';void refreshAssignmentField({loadTask:false})},20)},true);
let planlyWasHidden=document.visibilityState==='hidden';
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){planlyWasHidden=true;return}if(document.visibilityState==='visible'&&planlyWasHidden){planlyWasHidden=false;kickForegroundHouseholdSync();window.dispatchEvent(new CustomEvent('planly:foreground-resume'));}});
window.addEventListener('pageshow',e=>{if(e.persisted){kickForegroundHouseholdSync();window.dispatchEvent(new CustomEvent('planly:foreground-resume'));}});
window.addEventListener('online',()=>{setTimeout(scheduleGateRefresh,300);setTimeout(()=>void armHouseholdRealtime(),350);});
window.addEventListener('pagehide',()=>void stopHouseholdRealtime());
window.addEventListener('planly:household-ready',e=>{const detail=e?.detail||{},householdId=String(detail.householdId||''),userId=String(detail.userId||'');if(!userId){assignmentContext={householdId:'',userId:'',members:[],labels:new Map()};assignmentContextLoadedAt=Date.now();void stopHouseholdRealtime();return}const memberKey=JSON.stringify((Array.isArray(detail.members)?detail.members:[]).map(m=>[String(m.user_id||''),String(m.role||''),String(m.display_name||'')]));const currentKey=JSON.stringify((assignmentContext.members||[]).map(m=>[String(m.user_id||''),String(m.role||''),String(m.display_name||'')]));if(householdId===assignmentContext.householdId&&userId===assignmentContext.userId&&assignmentContextLoadedAt&&memberKey===currentKey)return;assignmentContextLoadedAt=0;void loadAssignmentContext(true).then(()=>{void refreshAssignmentField({loadTask:false});void armHouseholdRealtime()})});
installAssignmentStyle();bindPostLoginSync();refreshSharingGate();setTimeout(()=>{void loadAssignmentContext(true);void armHouseholdRealtime()},500);
})();