import { launch } from './harness.mjs';
import { ME } from './mock.mjs';
await fetch('http://localhost:8802/__switch?to=pr');
const h=await launch({uid:ME}); const {page:p,W,MOCK}=h; const q=(f,a)=>p.evaluate(f,a); const R={};
await p.clock.setFixedTime(new Date(process.env.CLOCK||'2026-09-30T21:00:00Z'));
await p.setViewportSize({width:390,height:844});
await p.goto('http://localhost:8802/planly/v2/'); await W(4000); await p.reload(); await W(10000);
const writes=[];p.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method())&&r.url().includes('/rest/v1/'))writes.push(r.method()+' '+r.url().split('/rest/v1/')[1].split('?')[0]+' '+(r.postData()||'').slice(0,160))});
await q(()=>document.querySelector('#planMyDayBtn')?.click());await W(800);
R.title1=await q(()=>document.querySelector('#planDayTitle')?.innerText);
// other-device edits while overlay open
const tiles=MOCK.db.planly_tasks.find(t=>t.client_id==='task-tiles');tiles.title='Order tiles (laptop edit)';tiles.data={...tiles.data,title:'Order tiles (laptop edit)',notes:'from laptop'};tiles.notes='from laptop';tiles.cloud_version=(tiles.cloud_version||1)+1;tiles.client_updated_at=Date.now()+1000;
const lau=MOCK.db.planly_tasks.find(t=>t.client_id==='task-laundry');lau.completed=true;lau.data={...lau.data,completed:true};lau.cloud_version=(lau.cloud_version||1)+1;lau.client_updated_at=Date.now()+1000;
await q(()=>{Object.defineProperty(document,'visibilityState',{value:'hidden',configurable:true});document.dispatchEvent(new Event('visibilitychange'))});await W(800);
await q(()=>{Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});document.dispatchEvent(new Event('visibilitychange'))});await W(3500);
R.liveAfterSync=await q(()=>{const s=localStorage;let out=[];for(const k of Object.keys(s)){const v=s.getItem(k)||'';if(v.includes('laptop edit'))out.push(k)}return out});
const next=async()=>{await q(()=>document.querySelector('#planDayNext')?.click());await W(700)};
await next();await next();await next();
R.step4=await q(()=>document.querySelector('#planDayTitle')?.innerText);
R.chores=await q(()=>[...document.querySelectorAll('.planChoreList>div')].map(d=>d.innerText.replace(/\n/g,' | ')));
await q(()=>[...document.querySelectorAll('.planChoreList .checkBtn')].find(x=>/Partner shared task/.test(x.getAttribute('aria-label')))?.click());await W(800);
await next();
await q(()=>document.querySelectorAll('.planSuggestedTimes input').forEach(i=>{if(!i.checked)i.click()}));await W(300);
R.times=await q(()=>[...document.querySelectorAll('.planSuggestedTimes label')].map(l=>l.innerText.replace(/\n/g,' | ')+(l.querySelector('input').checked?' [x]':'')));
await q(()=>document.querySelector('#planDayNext')?.click());await W(7000);
const row=id=>{const t=MOCK.db.planly_tasks.find(t=>t.client_id===id);return t&&{title:t.data?.title,time:t.data?.time,date:t.data?.date,pinned:t.data?.pinned,completed:t.completed,completed_by:t.completed_by?.slice(0,4)}};
R.dbTiles=row('task-tiles');R.dbLaundry=row('task-laundry');R.dbGroceries=row('task-groceries');R.dbPartnerChore=row('task-partner-assigned');
R.writes=writes.map(w=>w.slice(0,110));
R.homeDone=await q(async()=>{document.querySelector('[data-section="home"]')?.click();await new Promise(r=>setTimeout(r,1200));return [...document.querySelectorAll('#view *')].map(e=>e.childElementCount===0?e.textContent:'').join(' ').match(/Partner shared task[^A-Z]{0,60}/g)});
R.errors=h.errors;for(const [k,v] of Object.entries(R))console.log(k,JSON.stringify(v));await h.browser.close();
